kinematic_arbiter: kinematic_arbiter::sensors::PoseSensorModel Class Reference
kinematic_arbiter::sensors::PoseSensorModel Class Reference
7DOF pose measurement model (position + orientation)
#include <pose_sensor_model.hpp>
Classes
struct MeasurementIndex
Indices for accessing pose measurement components.
Public Types
using Base = core::MeasurementModelInterface
using StateVector = typename Base::StateVector
using Vector = Eigen::Matrix< double, kMeasurementDimension, 1 >
using Jacobian = Eigen::Matrix< double, kMeasurementDimension, core::StateIndex::kFullStateSize >
using Covariance = Eigen::Matrix< double, kMeasurementDimension, kMeasurementDimension >
using StateFlags = typename Base::StateFlags
Public Types inherited from kinematic_arbiter::core::MeasurementModelInterface
using StateVector = Eigen::Matrix< double, StateSize, 1 >
using StateCovariance = Eigen::Matrix< double, StateSize, StateSize >
using DynamicVector = Eigen::Matrix< double, Eigen::Dynamic, 1, Eigen::ColMajor, kMaxMeasurementDim, 1 >
using DynamicCovariance = Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor, kMaxMeasurementDim, kMaxMeasurementDim >
using DynamicJacobian = Eigen::Matrix< double, Eigen::Dynamic, StateSize, Eigen::ColMajor, kMaxMeasurementDim, StateSize >
using StateFlags = Eigen::Array< bool, StateSize, 1 >
Public Member Functions
PoseSensorModel (const Eigen::Isometry3d &sensor_pose_in_body_frame=Eigen::Isometry3d::Identity(), const ValidationParams &params=ValidationParams())
Constructor.
void reset () override
Reset the measurement model to initial state.
DynamicVector PredictMeasurement (const StateVector &state) const override
Predict measurement from state.
DynamicJacobian GetMeasurementJacobian (const StateVector &) const override
Compute measurement Jacobian.
StateFlags GetInitializableStates () const override
Get states that this sensor can directly initialize.
StateFlags InitializeState (const DynamicVector &measurement, const StateFlags &, StateVector &state, StateCovariance &covariance) const override
Initialize state from pose measurement.
Public Member Functions inherited from kinematic_arbiter::core::MeasurementModelInterface
MeasurementModelInterface (SensorType type, const Eigen::Isometry3d &sensor_pose_in_body_frame=Eigen::Isometry3d::Identity(), const ValidationParams &params=ValidationParams(), const DynamicCovariance &measurement_covariance=Eigen::Matrix< double, kMaxMeasurementDim, kMaxMeasurementDim >::Identity())
Constructor.
virtual ~MeasurementModelInterface ()=default
Virtual destructor.
virtual Eigen::Matrix< double, 6, 1 > GetPredictionModelInputs (const StateVector &, const StateCovariance &, const DynamicVector &, double) const
Get the inputs to the prediction model.
bool CanPredictInputAccelerations () const
Get whether the prediction model can predict input accelerations.
const DynamicCovariance & GetMeasurementCovariance () const
Get current measurement covariance.
void SetValidationParams (const ValidationParams &params)
Set the validation parameters.
const ValidationParams & GetValidationParams () const
Get the current validation parameters.
MeasurementAuxData ComputeAuxiliaryData (const StateVector &state, const StateCovariance &state_covariance, const DynamicVector &measurement) const
Compute auxiliary measurement data for use in various algorithms.
bool ValidateAuxiliaryData (const MeasurementAuxData &aux_data) const
Validate auxiliary measurement data (innovation, jacobian, covariance)
bool ValidateAndMediate (const StateVector &state, const StateCovariance &state_covariance, const double &measurement_timestamp, const DynamicVector &measurement, MeasurementAuxData &aux_data)
Perform the validation and mediation process.
bool GetSensorPoseInBodyFrame (Eigen::Isometry3d &pose) const
Get sensor pose in body frame.
bool GetBodyToSensorTransform (Eigen::Isometry3d &pose) const
Get body to sensor transform.
bool SetSensorPoseInBodyFrame (const Eigen::Isometry3d &pose)
Set sensor pose in body frame.
SensorType GetModelType () const
Get the type of this sensor model (non-virtual)
bool ValidateMeasurementAndTime (const DynamicVector &measurement, double timestamp, double reference_time, double max_delay_window) const
Validate measurement and timestamp before any expensive operations.
Static Public Attributes
static constexpr int kMeasurementDimension = core::MeasurementDimension<core::SensorType::Pose>::value
Static Public Attributes inherited from kinematic_arbiter::core::MeasurementModelInterface
static constexpr int StateSize = StateIndex::kFullStateSize
Additional Inherited Members
Protected Member Functions inherited from kinematic_arbiter::core::MeasurementModelInterface
void ValidateMeasurementSize (const DynamicVector &measurement) const
Validate measurement size based on sensor type.
Protected Attributes inherited from kinematic_arbiter::core::MeasurementModelInterface
Eigen::Isometry3d sensor_pose_in_body_frame_ = Eigen::Isometry3d::Identity()
Eigen::Isometry3d body_to_sensor_transform_ = Eigen::Isometry3d::Identity()
DynamicCovariance measurement_covariance_
ValidationParams validation_params_
bool can_predict_input_accelerations_ = false
MeasurementData previous_measurement_data_
SensorType type_ = SensorType::Unknown
Detailed Description
7DOF pose measurement model (position + orientation)
Models a sensor that measures position and orientation in 3D space. Measurement vector is [x, y, z, qw, qx, qy, qz]' where [qw, qx, qy, qz] represents orientation as a quaternion.
Definition at line 16 of file pose_sensor_model.hpp.
Member Typedef Documentation
Base
using kinematic_arbiter::sensors::PoseSensorModel::Base = core::MeasurementModelInterface
Definition at line 20 of file pose_sensor_model.hpp.
Covariance
using kinematic_arbiter::sensors::PoseSensorModel::Covariance = Eigen::Matrix<double, kMeasurementDimension, kMeasurementDimension>
Definition at line 24 of file pose_sensor_model.hpp.
Jacobian
using kinematic_arbiter::sensors::PoseSensorModel::Jacobian = Eigen::Matrix<double, kMeasurementDimension, core::StateIndex::kFullStateSize>
Definition at line 23 of file pose_sensor_model.hpp.
StateFlags
using kinematic_arbiter::sensors::PoseSensorModel::StateFlags = typename Base::StateFlags
Definition at line 25 of file pose_sensor_model.hpp.
StateVector
using kinematic_arbiter::sensors::PoseSensorModel::StateVector = typename Base::StateVector
Definition at line 21 of file pose_sensor_model.hpp.
Vector
using kinematic_arbiter::sensors::PoseSensorModel::Vector = Eigen::Matrix<double, kMeasurementDimension, 1>
Definition at line 22 of file pose_sensor_model.hpp.
Constructor & Destructor Documentation
PoseSensorModel()
kinematic_arbiter::sensors::PoseSensorModel::PoseSensorModel (const Eigen::Isometry3d & sensor_pose_in_body_frame = Eigen::Isometry3d::Identity(), const ValidationParams & params = ValidationParams()) inline explicit
Constructor.
Parameters
sensor_pose_in_body_frame Transform from body to sensor frame
params Validation parameters
Definition at line 48 of file pose_sensor_model.hpp.
     : Base(core::SensorType::Pose, sensor_pose_in_body_frame, params, Covariance::Identity()) {}
Member Function Documentation
GetInitializableStates()
StateFlags kinematic_arbiter::sensors::PoseSensorModel::GetInitializableStates () const inline override virtual
Get states that this sensor can directly initialize.
Pose sensor provides both position and orientation measurements, so it can directly initialize these state components.
Returns
Flags for initializable states
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 153 of file pose_sensor_model.hpp.
{
     StateFlags flags = StateFlags::Zero();
     // Pose sensor can initialize position
     flags[core::StateIndex::Position::X] = true;
     flags[core::StateIndex::Position::Y] = true;
     flags[core::StateIndex::Position::Z] = true;
     // Pose sensor can initialize quaternion
     flags[core::StateIndex::Quaternion::W] = true;
     flags[core::StateIndex::Quaternion::X] = true;
     flags[core::StateIndex::Quaternion::Y] = true;
     flags[core::StateIndex::Quaternion::Z] = true;
     return flags;
   }
References kinematic_arbiter::core::StateIndex::Quaternion::W, kinematic_arbiter::core::StateIndex::Position::X, kinematic_arbiter::core::StateIndex::Quaternion::X, kinematic_arbiter::core::StateIndex::Position::Y, kinematic_arbiter::core::StateIndex::Quaternion::Y, kinematic_arbiter::core::StateIndex::Position::Z, and kinematic_arbiter::core::StateIndex::Quaternion::Z.
GetMeasurementJacobian()
DynamicJacobian kinematic_arbiter::sensors::PoseSensorModel::GetMeasurementJacobian (const StateVector &) const inline override virtual
Compute measurement Jacobian.
Parameters
state Current state estimate (unused in this implementation as Jacobian is constant)
Returns
Jacobian of measurement with respect to state
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 110 of file pose_sensor_model.hpp.
{
     Jacobian jacobian = Jacobian::Zero();
     // Position part of the Jacobian - derivative with respect to position is identity
     jacobian.block<3, 3>(MeasurementIndex::X, core::StateIndex::Position::X) =
         Eigen::Matrix3d::Identity();
     // Remove coupling between linear and angular position in the jacobian by
     // setting to zero. Derivation of partial of position with respect to the
     // rotation in quaternion form can be found here:
     // http://www.iri.upc.edu/people/jsola/JoanSola/objectes/notes/kinematics.pdf
     jacobian.block<3, 4>(MeasurementIndex::X, core::StateIndex::Quaternion::W) =
         Eigen::Matrix<double, 3, 4>::Zero();
     // Extract sensor-in-body quaternion components (q2)
     const Eigen::Quaterniond q2(sensor_pose_in_body_frame_.rotation());
     const double a2 = q2.w(), b2 = q2.x(), c2 = q2.y(), d2 = q2.z();
     // Quaternion Jacobian matrix - exactly matching the first provided formulation
     Eigen::Matrix4d quaternion_product_jacobian;
     quaternion_product_jacobian <<
         // clang-format off
          a2,  b2,  c2,  d2,
         -b2,  a2,  d2, -c2,
         -c2, -d2,  a2,  b2,
         -d2,  c2, -b2,  a2;
         // clang-format on
     // Fill the quaternion part of the measurement Jacobian
     jacobian.block<4, 4>(MeasurementIndex::QW, core::StateIndex::Quaternion::W) =
         quaternion_product_jacobian;
     return jacobian;
   }
References kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::QW, kinematic_arbiter::core::MeasurementModelInterface::sensor_pose_in_body_frame_, kinematic_arbiter::core::StateIndex::Quaternion::W, kinematic_arbiter::core::StateIndex::Position::X, and kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::X.
InitializeState()
StateFlags kinematic_arbiter::sensors::PoseSensorModel::InitializeState (const DynamicVector & measurement, const StateFlags & , StateVector & state, StateCovariance & covariance) const inline override virtual
Initialize state from pose measurement.
Initializes position and orientation states from sensor measurement, accounting for sensor-to-body frame transformation.
Parameters
measurement Pose measurement [x, y, z, qw, qx, qy, qz]
valid_states Flags indicating which states are valid
state State vector to update
covariance State covariance to update
Returns
Flags indicating which states were initialized
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 182 of file pose_sensor_model.hpp.
{
         ValidateMeasurementSize(measurement);
     StateFlags initialized_states = StateFlags::Zero();
     // Extract position and orientation from measurement
     Eigen::Vector3d sensor_position = measurement.segment<3>(MeasurementIndex::X);
     Eigen::Quaterniond sensor_orientation(
         measurement(MeasurementIndex::QW),
         measurement(MeasurementIndex::QX),
         measurement(MeasurementIndex::QY),
         measurement(MeasurementIndex::QZ)
     );
     // Extract the sensor-to-body transform components
     Eigen::Vector3d trans_b_s = sensor_pose_in_body_frame_.translation();
     Eigen::Quaterniond rot_b_s(sensor_pose_in_body_frame_.rotation());
     // Transform from sensor to body frame
     // For orientation: q_body = q_sensor * (q_sensor_in_body)^-1
     Eigen::Quaterniond body_orientation = sensor_orientation * rot_b_s.inverse();
     body_orientation.normalize();  // Ensure unit quaternion
     // For position: p_body = p_sensor - R_body_to_global * p_sensor_in_body
     Eigen::Vector3d body_position = sensor_position - body_orientation * trans_b_s;
     // Update state with initialized values
     state.segment<3>(core::StateIndex::Position::Begin()) = body_position;
     state(core::StateIndex::Quaternion::W) = body_orientation.w();
     state(core::StateIndex::Quaternion::X) = body_orientation.x();
     state(core::StateIndex::Quaternion::Y) = body_orientation.y();
     state(core::StateIndex::Quaternion::Z) = body_orientation.z();
     // Transform measurement covariance to state covariance
     // Note: This is a simplified approach; a more rigorous implementation would
     // apply the proper uncertainty transformation through the Jacobian
     // For position covariance (direct mapping with lever arm effects)
     Eigen::Matrix3d pos_cov = measurement_covariance_.block<3, 3>(0, 0);
     // For quaternion covariance (simplified transfer from measurement)
     Eigen::Matrix4d quat_cov = measurement_covariance_.block<4, 4>(3, 3);
     // Update covariance blocks
     covariance.block<3, 3>(
         core::StateIndex::Position::Begin(),
         core::StateIndex::Position::Begin()) = pos_cov;
     covariance.block<4, 4>(
         core::StateIndex::Quaternion::Begin(),
         core::StateIndex::Quaternion::Begin()) = quat_cov;
     // Mark states as initialized
     initialized_states[core::StateIndex::Position::X] = true;
     initialized_states[core::StateIndex::Position::Y] = true;
     initialized_states[core::StateIndex::Position::Z] = true;
     initialized_states[core::StateIndex::Quaternion::W] = true;
     initialized_states[core::StateIndex::Quaternion::X] = true;
     initialized_states[core::StateIndex::Quaternion::Y] = true;
     initialized_states[core::StateIndex::Quaternion::Z] = true;
     return initialized_states;
   }
References kinematic_arbiter::core::StateIndex::Position::Begin(), kinematic_arbiter::core::StateIndex::Quaternion::Begin(), kinematic_arbiter::core::MeasurementModelInterface::measurement_covariance_, kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::QW, kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::QX, kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::QY, kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::QZ, kinematic_arbiter::core::MeasurementModelInterface::sensor_pose_in_body_frame_, kinematic_arbiter::core::MeasurementModelInterface::ValidateMeasurementSize(), kinematic_arbiter::core::StateIndex::Quaternion::W, kinematic_arbiter::core::StateIndex::Position::X, kinematic_arbiter::core::StateIndex::Quaternion::X, kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::X, kinematic_arbiter::core::StateIndex::Position::Y, kinematic_arbiter::core::StateIndex::Quaternion::Y, kinematic_arbiter::core::StateIndex::Position::Z, and kinematic_arbiter::core::StateIndex::Quaternion::Z.
PredictMeasurement()
DynamicVector kinematic_arbiter::sensors::PoseSensorModel::PredictMeasurement (const StateVector & state) const inline override virtual
Predict measurement from state.
Parameters
state Current state estimate
Returns
Expected measurement [x, y, z, qw, qx, qy, qz]'
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 67 of file pose_sensor_model.hpp.
{
     Vector predicted_measurement = Vector::Zero();
     // Extract position from state
     Eigen::Vector3d position = state.segment<3>(core::StateIndex::Position::X);
     // Extract orientation quaternion from state
     Eigen::Quaterniond orientation(
         state(core::StateIndex::Quaternion::W),
         state(core::StateIndex::Quaternion::X),
         state(core::StateIndex::Quaternion::Y),
         state(core::StateIndex::Quaternion::Z)
     );
     // Extract the sensor-to-body transform components
     Eigen::Vector3d trans_b_s = sensor_pose_in_body_frame_.translation();
     Eigen::Quaterniond rot_b_s(sensor_pose_in_body_frame_.rotation());
     // Compute predicted position in global frame
     // p_sensor_global = p_body + R_body_to_global * p_sensor_in_body
     Eigen::Vector3d predicted_position = position + orientation * trans_b_s;
     // Compute predicted orientation in global frame
     // q_sensor_global = q_body * q_sensor_in_body
     Eigen::Quaterniond predicted_orientation = orientation * rot_b_s;
     predicted_orientation.normalize(); // Ensure unit quaternion
     // Fill measurement vector
     predicted_measurement.segment<3>(MeasurementIndex::X) = predicted_position;
     predicted_measurement(MeasurementIndex::QW) = predicted_orientation.w();
     predicted_measurement(MeasurementIndex::QX) = predicted_orientation.x();
     predicted_measurement(MeasurementIndex::QY) = predicted_orientation.y();
     predicted_measurement(MeasurementIndex::QZ) = predicted_orientation.z();
     return predicted_measurement;
   }
References kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::QW, kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::QX, kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::QY, kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::QZ, kinematic_arbiter::core::MeasurementModelInterface::sensor_pose_in_body_frame_, kinematic_arbiter::core::StateIndex::Quaternion::W, kinematic_arbiter::core::StateIndex::Position::X, kinematic_arbiter::core::StateIndex::Quaternion::X, kinematic_arbiter::sensors::PoseSensorModel::MeasurementIndex::X, kinematic_arbiter::core::StateIndex::Quaternion::Y, and kinematic_arbiter::core::StateIndex::Quaternion::Z.
reset()
void kinematic_arbiter::sensors::PoseSensorModel::reset () inline override virtual
Reset the measurement model to initial state.
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 57 of file pose_sensor_model.hpp.
{
       measurement_covariance_ = Covariance::Identity();
     }
References kinematic_arbiter::core::MeasurementModelInterface::measurement_covariance_.
Member Data Documentation
kMeasurementDimension
constexpr int kinematic_arbiter::sensors::PoseSensorModel::kMeasurementDimension = core::MeasurementDimension<core::SensorType::Pose>::value static constexpr
Definition at line 19 of file pose_sensor_model.hpp.
Referenced by kinematic_arbiter::ros2::PoseSensorHandler::msgToVector().
The documentation for this class was generated from the following file:
/home/spencer/ros2workspace/src/kinematic_arbiter/include/kinematic_arbiter/sensors/pose_sensor_model.hpp