kinematic_arbiter: kinematic_arbiter::sensors::BodyVelocitySensorModel Class Reference
kinematic_arbiter::sensors::BodyVelocitySensorModel Class Reference
Body velocity measurement model (linear + angular velocity)
#include <body_velocity_sensor_model.hpp>
Classes
struct MeasurementIndex
Indices for accessing body velocity measurement components.
Public Types
using Base = core::MeasurementModelInterface
using StateVector = typename Base::StateVector
using Vector = Eigen::Matrix< double, kMeasurementDimension, 1 >
using Jacobian = Eigen::Matrix< double, kMeasurementDimension, core::StateIndex::kFullStateSize >
using Covariance = Eigen::Matrix< double, kMeasurementDimension, kMeasurementDimension >
using StateFlags = typename Base::StateFlags
Public Types inherited from kinematic_arbiter::core::MeasurementModelInterface
using StateVector = Eigen::Matrix< double, StateSize, 1 >
using StateCovariance = Eigen::Matrix< double, StateSize, StateSize >
using DynamicVector = Eigen::Matrix< double, Eigen::Dynamic, 1, Eigen::ColMajor, kMaxMeasurementDim, 1 >
using DynamicCovariance = Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor, kMaxMeasurementDim, kMaxMeasurementDim >
using DynamicJacobian = Eigen::Matrix< double, Eigen::Dynamic, StateSize, Eigen::ColMajor, kMaxMeasurementDim, StateSize >
using StateFlags = Eigen::Array< bool, StateSize, 1 >
Public Member Functions
BodyVelocitySensorModel (const Eigen::Isometry3d &sensor_pose_in_body_frame=Eigen::Isometry3d::Identity(), const ValidationParams &params=ValidationParams())
Constructor.
void reset () override
Reset the measurement model to initial state.
DynamicVector PredictMeasurement (const StateVector &state) const override
Predict measurement from state.
DynamicJacobian GetMeasurementJacobian (const StateVector &) const override
Compute measurement Jacobian.
StateFlags GetInitializableStates () const override
Get states that this sensor can directly initialize.
StateFlags InitializeState (const DynamicVector &measurement, const StateFlags &, StateVector &state, StateCovariance &covariance) const override
Initialize state from body velocity measurement.
Public Member Functions inherited from kinematic_arbiter::core::MeasurementModelInterface
MeasurementModelInterface (SensorType type, const Eigen::Isometry3d &sensor_pose_in_body_frame=Eigen::Isometry3d::Identity(), const ValidationParams &params=ValidationParams(), const DynamicCovariance &measurement_covariance=Eigen::Matrix< double, kMaxMeasurementDim, kMaxMeasurementDim >::Identity())
Constructor.
virtual ~MeasurementModelInterface ()=default
Virtual destructor.
virtual Eigen::Matrix< double, 6, 1 > GetPredictionModelInputs (const StateVector &, const StateCovariance &, const DynamicVector &, double) const
Get the inputs to the prediction model.
bool CanPredictInputAccelerations () const
Get whether the prediction model can predict input accelerations.
const DynamicCovariance & GetMeasurementCovariance () const
Get current measurement covariance.
void SetValidationParams (const ValidationParams &params)
Set the validation parameters.
const ValidationParams & GetValidationParams () const
Get the current validation parameters.
MeasurementAuxData ComputeAuxiliaryData (const StateVector &state, const StateCovariance &state_covariance, const DynamicVector &measurement) const
Compute auxiliary measurement data for use in various algorithms.
bool ValidateAuxiliaryData (const MeasurementAuxData &aux_data) const
Validate auxiliary measurement data (innovation, jacobian, covariance)
bool ValidateAndMediate (const StateVector &state, const StateCovariance &state_covariance, const double &measurement_timestamp, const DynamicVector &measurement, MeasurementAuxData &aux_data)
Perform the validation and mediation process.
bool GetSensorPoseInBodyFrame (Eigen::Isometry3d &pose) const
Get sensor pose in body frame.
bool GetBodyToSensorTransform (Eigen::Isometry3d &pose) const
Get body to sensor transform.
bool SetSensorPoseInBodyFrame (const Eigen::Isometry3d &pose)
Set sensor pose in body frame.
SensorType GetModelType () const
Get the type of this sensor model (non-virtual)
bool ValidateMeasurementAndTime (const DynamicVector &measurement, double timestamp, double reference_time, double max_delay_window) const
Validate measurement and timestamp before any expensive operations.
Static Public Attributes
static constexpr int kMeasurementDimension = core::MeasurementDimension<core::SensorType::BodyVelocity>::value
Static Public Attributes inherited from kinematic_arbiter::core::MeasurementModelInterface
static constexpr int StateSize = StateIndex::kFullStateSize
Additional Inherited Members
Protected Member Functions inherited from kinematic_arbiter::core::MeasurementModelInterface
void ValidateMeasurementSize (const DynamicVector &measurement) const
Validate measurement size based on sensor type.
Protected Attributes inherited from kinematic_arbiter::core::MeasurementModelInterface
Eigen::Isometry3d sensor_pose_in_body_frame_ = Eigen::Isometry3d::Identity()
Eigen::Isometry3d body_to_sensor_transform_ = Eigen::Isometry3d::Identity()
DynamicCovariance measurement_covariance_
ValidationParams validation_params_
bool can_predict_input_accelerations_ = false
MeasurementData previous_measurement_data_
SensorType type_ = SensorType::Unknown
Detailed Description
Body velocity measurement model (linear + angular velocity)
Models a sensor that measures linear and angular velocities in the body frame. Measurement vector is [vx, vy, vz, wx, wy, wz]' where [vx, vy, vz] represents linear velocity and [wx, wy, wz] represents angular velocity.
Definition at line 17 of file body_velocity_sensor_model.hpp.
Member Typedef Documentation
Base
using kinematic_arbiter::sensors::BodyVelocitySensorModel::Base = core::MeasurementModelInterface
Definition at line 20 of file body_velocity_sensor_model.hpp.
Covariance
using kinematic_arbiter::sensors::BodyVelocitySensorModel::Covariance = Eigen::Matrix<double, kMeasurementDimension, kMeasurementDimension>
Definition at line 25 of file body_velocity_sensor_model.hpp.
Jacobian
using kinematic_arbiter::sensors::BodyVelocitySensorModel::Jacobian = Eigen::Matrix<double, kMeasurementDimension, core::StateIndex::kFullStateSize>
Definition at line 24 of file body_velocity_sensor_model.hpp.
StateFlags
using kinematic_arbiter::sensors::BodyVelocitySensorModel::StateFlags = typename Base::StateFlags
Definition at line 26 of file body_velocity_sensor_model.hpp.
StateVector
using kinematic_arbiter::sensors::BodyVelocitySensorModel::StateVector = typename Base::StateVector
Definition at line 22 of file body_velocity_sensor_model.hpp.
Vector
using kinematic_arbiter::sensors::BodyVelocitySensorModel::Vector = Eigen::Matrix<double, kMeasurementDimension, 1>
Definition at line 23 of file body_velocity_sensor_model.hpp.
Constructor & Destructor Documentation
BodyVelocitySensorModel()
kinematic_arbiter::sensors::BodyVelocitySensorModel::BodyVelocitySensorModel (const Eigen::Isometry3d & sensor_pose_in_body_frame = Eigen::Isometry3d::Identity(), const ValidationParams & params = ValidationParams()) inline explicit
Constructor.
Parameters
sensor_pose_in_body_frame Transform from body to sensor frame
params Validation parameters
Definition at line 49 of file body_velocity_sensor_model.hpp.
     : Base(core::SensorType::BodyVelocity, sensor_pose_in_body_frame, params, Covariance::Identity()) {}
Member Function Documentation
GetInitializableStates()
StateFlags kinematic_arbiter::sensors::BodyVelocitySensorModel::GetInitializableStates () const inline override virtual
Get states that this sensor can directly initialize.
Body velocity sensors can initialize linear and angular velocity states.
Returns
Flags for initializable states
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 167 of file body_velocity_sensor_model.hpp.
{
     StateFlags flags = StateFlags::Zero();
     // Body velocity sensor can initialize all velocity states
     flags[core::StateIndex::LinearVelocity::X] = true;
     flags[core::StateIndex::LinearVelocity::Y] = true;
     flags[core::StateIndex::LinearVelocity::Z] = true;
     flags[core::StateIndex::AngularVelocity::X] = true;
     flags[core::StateIndex::AngularVelocity::Y] = true;
     flags[core::StateIndex::AngularVelocity::Z] = true;
     return flags;
   }
References kinematic_arbiter::core::StateIndex::LinearVelocity::X, kinematic_arbiter::core::StateIndex::AngularVelocity::X, kinematic_arbiter::core::StateIndex::LinearVelocity::Y, kinematic_arbiter::core::StateIndex::AngularVelocity::Y, kinematic_arbiter::core::StateIndex::LinearVelocity::Z, and kinematic_arbiter::core::StateIndex::AngularVelocity::Z.
GetMeasurementJacobian()
DynamicJacobian kinematic_arbiter::sensors::BodyVelocitySensorModel::GetMeasurementJacobian (const StateVector &) const inline override virtual
Compute measurement Jacobian.
Parameters
state Current state estimate
Returns
Jacobian of measurement with respect to state
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 110 of file body_velocity_sensor_model.hpp.
{
     Jacobian jacobian = Jacobian::Zero();
     // Extract transform parameters
     Eigen::Vector3d sensor_offset = sensor_pose_in_body_frame_.translation();
     Eigen::Matrix3d body_to_sensor_rotation = sensor_pose_in_body_frame_.rotation().transpose();
     // ===== LINEAR VELOCITY JACOBIAN =====
     // Linear velocity w.r.t. linear velocity - simple rotation from body to sensor frame
     jacobian.block<3, 3>(MeasurementIndex::VX, core::StateIndex::LinearVelocity::X) = body_to_sensor_rotation;
     // Linear velocity w.r.t. angular velocity - lever arm effect
     // The lever arm effect can be represented by partial derivatives of the cross product
     // These derivatives have a standard form for cross products
     // Define cross product derivatives in a more compact way
     // Following standard notation where [r] is the skew-symmetric matrix of vector r
     // For a sensor at position r, the derivatives of r with respect to each  component
     // correspond to the columns of a skew matrix of r
     // Create skew-symmetric matrix of the sensor offset
     Eigen::Matrix3d skew_offset = Eigen::Matrix3d::Zero();
     skew_offset <<
         0,              -sensor_offset.z(),  sensor_offset.y(),
         sensor_offset.z(),  0,              -sensor_offset.x(),
        -sensor_offset.y(),  sensor_offset.x(),  0;
     // Each column of this matrix represents the lever arm effect for one angular velocity component
     // Extract columns for better readability
     Eigen::Vector3d lever_arm_effect_wx = -skew_offset.col(0);  // Effect of _x
     Eigen::Vector3d lever_arm_effect_wy = -skew_offset.col(1);  // Effect of _y
     Eigen::Vector3d lever_arm_effect_wz = -skew_offset.col(2);  // Effect of _z
     // Apply body-to-sensor rotation and fill Jacobian
     jacobian.block<3, 1>(MeasurementIndex::VX, core::StateIndex::AngularVelocity::X) =
         body_to_sensor_rotation * lever_arm_effect_wx;
     jacobian.block<3, 1>(MeasurementIndex::VX, core::StateIndex::AngularVelocity::Y) =
         body_to_sensor_rotation * lever_arm_effect_wy;
     jacobian.block<3, 1>(MeasurementIndex::VX, core::StateIndex::AngularVelocity::Z) =
         body_to_sensor_rotation * lever_arm_effect_wz;
     // ===== ANGULAR VELOCITY JACOBIAN =====
     // Angular velocity w.r.t. angular velocity - simple rotation from body to sensor frame
     jacobian.block<3, 3>(MeasurementIndex::WX, core::StateIndex::AngularVelocity::X) = body_to_sensor_rotation;
     return jacobian;
   }
References kinematic_arbiter::core::MeasurementModelInterface::sensor_pose_in_body_frame_, kinematic_arbiter::sensors::BodyVelocitySensorModel::MeasurementIndex::VX, kinematic_arbiter::sensors::BodyVelocitySensorModel::MeasurementIndex::WX, kinematic_arbiter::core::StateIndex::LinearVelocity::X, kinematic_arbiter::core::StateIndex::AngularVelocity::X, kinematic_arbiter::core::StateIndex::AngularVelocity::Y, and kinematic_arbiter::core::StateIndex::AngularVelocity::Z.
InitializeState()
StateFlags kinematic_arbiter::sensors::BodyVelocitySensorModel::InitializeState (const DynamicVector & measurement, const StateFlags & , StateVector & state, StateCovariance & covariance) const inline override virtual
Initialize state from body velocity measurement.
Initializes linear and angular velocity states based on the measurement, properly accounting for lever arm effects between sensor and body frame.
Parameters
measurement Velocity measurement [vx, vy, vz, wx, wy, wz]
valid_states Flags indicating which states are valid for initialization
state State vector to update
covariance State covariance to update
Returns
Flags indicating which states were initialized
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 193 of file body_velocity_sensor_model.hpp.
{
     ValidateMeasurementSize(measurement);
     StateFlags initialized_states = StateFlags::Zero();
     // Extract measurement components in sensor frame
     const Eigen::Vector3d sensor_lin_vel = measurement.segment<3>(0);
     const Eigen::Vector3d sensor_ang_vel = measurement.segment<3>(3);
       // Extract the sensor-to-body transform components
       const Eigen::Vector3d trans_b_s = sensor_pose_in_body_frame_.translation();
       const Eigen::Matrix3d rot_b_s = sensor_pose_in_body_frame_.rotation();
       // Calculate the skew-symmetric matrix for the cross product:   r
       auto skew_matrix = [](const Eigen::Vector3d& v) -> Eigen::Matrix3d {
         Eigen::Matrix3d skew;
         skew << 0, -v(2), v(1),
                 v(2), 0, -v(0),
                 -v(1), v(0), 0;
         return skew;
       };
       // First, compute body angular velocity
       const Eigen::Vector3d body_ang_vel = rot_b_s * sensor_ang_vel;
       // Convert sensor linear velocity to body frame
       const Eigen::Vector3d sensor_lin_vel_in_body = rot_b_s * sensor_lin_vel;
       // Account for the lever arm effect
       const Eigen::Vector3d lever_arm_effect = skew_matrix(body_ang_vel) * trans_b_s;
       // Compute body linear velocity
       const Eigen::Vector3d body_lin_vel = sensor_lin_vel_in_body - lever_arm_effect;
       // Initialize state vector
       state.segment<3>(core::StateIndex::LinearVelocity::Begin()) = body_lin_vel;
       state.segment<3>(core::StateIndex::AngularVelocity::Begin()) = body_ang_vel;
       // Set all velocity states as initialized
       initialized_states[core::StateIndex::LinearVelocity::X] = true;
       initialized_states[core::StateIndex::LinearVelocity::Y] = true;
       initialized_states[core::StateIndex::LinearVelocity::Z] = true;
       initialized_states[core::StateIndex::AngularVelocity::X] = true;
       initialized_states[core::StateIndex::AngularVelocity::Y] = true;
       initialized_states[core::StateIndex::AngularVelocity::Z] = true;
       // Transform covariance from sensor to body frame
       // For angular velocity (straightforward rotation)
       Eigen::Matrix3d ang_vel_cov = rot_b_s *
           measurement_covariance_.block<3, 3>(3, 3) *
           rot_b_s.transpose();
       // For linear velocity (approximate - ignoring cross-terms with angular velocity)
       Eigen::Matrix3d lin_vel_cov = rot_b_s *
           measurement_covariance_.block<3, 3>(0, 0) *
           rot_b_s.transpose();
       // Set covariance blocks in state covariance
       covariance.block<3, 3>(
           core::StateIndex::LinearVelocity::Begin(),
           core::StateIndex::LinearVelocity::Begin()) = lin_vel_cov;
       covariance.block<3, 3>(
           core::StateIndex::AngularVelocity::Begin(),
           core::StateIndex::AngularVelocity::Begin()) = ang_vel_cov;
     return initialized_states;
   }
References kinematic_arbiter::core::StateIndex::LinearVelocity::Begin(), kinematic_arbiter::core::StateIndex::AngularVelocity::Begin(), kinematic_arbiter::core::MeasurementModelInterface::measurement_covariance_, kinematic_arbiter::core::MeasurementModelInterface::sensor_pose_in_body_frame_, kinematic_arbiter::core::MeasurementModelInterface::ValidateMeasurementSize(), kinematic_arbiter::core::StateIndex::LinearVelocity::X, kinematic_arbiter::core::StateIndex::AngularVelocity::X, kinematic_arbiter::core::StateIndex::LinearVelocity::Y, kinematic_arbiter::core::StateIndex::AngularVelocity::Y, kinematic_arbiter::core::StateIndex::LinearVelocity::Z, and kinematic_arbiter::core::StateIndex::AngularVelocity::Z.
PredictMeasurement()
DynamicVector kinematic_arbiter::sensors::BodyVelocitySensorModel::PredictMeasurement (const StateVector & state) const inline override virtual
Predict measurement from state.
Parameters
state Current state estimate
Returns
Expected measurement [vx, vy, vz, wx, wy, wz]'
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 67 of file body_velocity_sensor_model.hpp.
{
     Vector predicted_measurement = Vector::Zero();
     // Extract linear velocity from state
     Eigen::Vector3d body_lin_vel = state.segment<3>(core::StateIndex::LinearVelocity::X);
     // Extract angular velocity from state
     Eigen::Vector3d body_ang_vel = state.segment<3>(core::StateIndex::AngularVelocity::X);
     // Extract the sensor-to-body transform components
     Eigen::Vector3d trans_b_s = sensor_pose_in_body_frame_.translation();
     Eigen::Matrix3d rot_b_s = sensor_pose_in_body_frame_.rotation();
     // Calculate the skew-symmetric matrix for the cross product:   r
     auto skew_matrix = [](const Eigen::Vector3d& v) -> Eigen::Matrix3d {
       Eigen::Matrix3d skew;
       skew << 0, -v(2), v(1),
               v(2), 0, -v(0),
               -v(1), v(0), 0;
       return skew;
     };
     // Calculate linear velocity at the sensor location in body frame
     // v_sensor = v_body +   r, where r is the position of the sensor in the body frame
     Eigen::Vector3d body_sensor_lin_vel = body_lin_vel + skew_matrix(body_ang_vel) * trans_b_s;
     // Transform velocities to sensor frame
     Eigen::Vector3d sensor_lin_vel = rot_b_s.transpose() * body_sensor_lin_vel;
     Eigen::Vector3d sensor_ang_vel = rot_b_s.transpose() * body_ang_vel;
     // Fill measurement vector
     predicted_measurement.segment<3>(MeasurementIndex::VX) = sensor_lin_vel;
     predicted_measurement.segment<3>(MeasurementIndex::WX) = sensor_ang_vel;
     return predicted_measurement;
   }
References kinematic_arbiter::core::MeasurementModelInterface::sensor_pose_in_body_frame_, kinematic_arbiter::sensors::BodyVelocitySensorModel::MeasurementIndex::VX, kinematic_arbiter::sensors::BodyVelocitySensorModel::MeasurementIndex::WX, kinematic_arbiter::core::StateIndex::LinearVelocity::X, and kinematic_arbiter::core::StateIndex::AngularVelocity::X.
reset()
void kinematic_arbiter::sensors::BodyVelocitySensorModel::reset () inline override virtual
Reset the measurement model to initial state.
Implements kinematic_arbiter::core::MeasurementModelInterface.
Definition at line 57 of file body_velocity_sensor_model.hpp.
{
       measurement_covariance_ = Covariance::Identity();
     }
References kinematic_arbiter::core::MeasurementModelInterface::measurement_covariance_.
Member Data Documentation
kMeasurementDimension
constexpr int kinematic_arbiter::sensors::BodyVelocitySensorModel::kMeasurementDimension = core::MeasurementDimension<core::SensorType::BodyVelocity>::value static constexpr
Definition at line 21 of file body_velocity_sensor_model.hpp.
Referenced by kinematic_arbiter::ros2::VelocitySensorHandler::msgToVector().
The documentation for this class was generated from the following file:
/home/spencer/ros2workspace/src/kinematic_arbiter/include/kinematic_arbiter/sensors/body_velocity_sensor_model.hpp