kinematic_arbiter: kinematic_arbiter::core::MeasurementModelInterface Class Reference
kinematic_arbiter::core::MeasurementModelInterface Class Reference abstract
Interface for measurement models with assumption validation.
#include <measurement_model_interface.hpp>
Classes
struct MeasurementAuxData
Core measurement auxiliary data that can be reused across algorithms.
struct MeasurementData
struct ValidationParams
Parameters for assumption validation.
Public Types
using StateVector = Eigen::Matrix< double, StateSize, 1 >
using StateCovariance = Eigen::Matrix< double, StateSize, StateSize >
using DynamicVector = Eigen::Matrix< double, Eigen::Dynamic, 1, Eigen::ColMajor, kMaxMeasurementDim, 1 >
using DynamicCovariance = Eigen::Matrix< double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor, kMaxMeasurementDim, kMaxMeasurementDim >
using DynamicJacobian = Eigen::Matrix< double, Eigen::Dynamic, StateSize, Eigen::ColMajor, kMaxMeasurementDim, StateSize >
using StateFlags = Eigen::Array< bool, StateSize, 1 >
Public Member Functions
MeasurementModelInterface (SensorType type, const Eigen::Isometry3d &sensor_pose_in_body_frame=Eigen::Isometry3d::Identity(), const ValidationParams &params=ValidationParams(), const DynamicCovariance &measurement_covariance=Eigen::Matrix< double, kMaxMeasurementDim, kMaxMeasurementDim >::Identity())
Constructor.
virtual void reset ()=0
Reset the measurement model to initial state.
virtual ~MeasurementModelInterface ()=default
Virtual destructor.
virtual DynamicVector PredictMeasurement (const StateVector &state) const =0
Predict expected measurement h(x) from state.
virtual DynamicJacobian GetMeasurementJacobian (const StateVector &state) const =0
Compute the measurement Jacobian H = ∂h/∂x.
virtual Eigen::Matrix< double, 6, 1 > GetPredictionModelInputs (const StateVector &, const StateCovariance &, const DynamicVector &, double) const
Get the inputs to the prediction model.
bool CanPredictInputAccelerations () const
Get whether the prediction model can predict input accelerations.
const DynamicCovariance & GetMeasurementCovariance () const
Get current measurement covariance.
void SetValidationParams (const ValidationParams &params)
Set the validation parameters.
const ValidationParams & GetValidationParams () const
Get the current validation parameters.
MeasurementAuxData ComputeAuxiliaryData (const StateVector &state, const StateCovariance &state_covariance, const DynamicVector &measurement) const
Compute auxiliary measurement data for use in various algorithms.
bool ValidateAuxiliaryData (const MeasurementAuxData &aux_data) const
Validate auxiliary measurement data (innovation, jacobian, covariance)
bool ValidateAndMediate (const StateVector &state, const StateCovariance &state_covariance, const double &measurement_timestamp, const DynamicVector &measurement, MeasurementAuxData &aux_data)
Perform the validation and mediation process.
bool GetSensorPoseInBodyFrame (Eigen::Isometry3d &pose) const
Get sensor pose in body frame.
bool GetBodyToSensorTransform (Eigen::Isometry3d &pose) const
Get body to sensor transform.
bool SetSensorPoseInBodyFrame (const Eigen::Isometry3d &pose)
Set sensor pose in body frame.
virtual StateFlags GetInitializableStates () const =0
Get the states that this sensor can directly initialize.
virtual StateFlags InitializeState (const DynamicVector &measurement, const StateFlags &valid_states, StateVector &state, StateCovariance &covariance) const =0
Initialize state components from a measurement.
SensorType GetModelType () const
Get the type of this sensor model (non-virtual)
bool ValidateMeasurementAndTime (const DynamicVector &measurement, double timestamp, double reference_time, double max_delay_window) const
Validate measurement and timestamp before any expensive operations.
Static Public Attributes
static constexpr int StateSize = StateIndex::kFullStateSize
Protected Member Functions
void ValidateMeasurementSize (const DynamicVector &measurement) const
Validate measurement size based on sensor type.
Protected Attributes
Eigen::Isometry3d sensor_pose_in_body_frame_ = Eigen::Isometry3d::Identity()
Eigen::Isometry3d body_to_sensor_transform_ = Eigen::Isometry3d::Identity()
DynamicCovariance measurement_covariance_
ValidationParams validation_params_
bool can_predict_input_accelerations_ = false
MeasurementData previous_measurement_data_
SensorType type_ = SensorType::Unknown
Private Member Functions
void UpdateCovariance (const DynamicVector &innovation)
Update measurement covariance with bounded innovation.
Detailed Description
Interface for measurement models with assumption validation.
Provides methods for predicting measurements, computing Jacobians, and validating filter assumptions using chi-squared testing.
Template Parameters
Type Sensor type that defines the measurement vector dimensions
Definition at line 28 of file measurement_model_interface.hpp.
Member Typedef Documentation
DynamicCovariance
using kinematic_arbiter::core::MeasurementModelInterface::DynamicCovariance = Eigen::Matrix<double, Eigen::Dynamic, Eigen::Dynamic, Eigen::ColMajor, kMaxMeasurementDim, kMaxMeasurementDim>
Definition at line 36 of file measurement_model_interface.hpp.
DynamicJacobian
using kinematic_arbiter::core::MeasurementModelInterface::DynamicJacobian = Eigen::Matrix<double, Eigen::Dynamic, StateSize, Eigen::ColMajor, kMaxMeasurementDim, StateSize>
Definition at line 37 of file measurement_model_interface.hpp.
DynamicVector
using kinematic_arbiter::core::MeasurementModelInterface::DynamicVector = Eigen::Matrix<double, Eigen::Dynamic, 1, Eigen::ColMajor, kMaxMeasurementDim, 1>
Definition at line 35 of file measurement_model_interface.hpp.
StateCovariance
using kinematic_arbiter::core::MeasurementModelInterface::StateCovariance = Eigen::Matrix<double, StateSize, StateSize>
Definition at line 34 of file measurement_model_interface.hpp.
StateFlags
using kinematic_arbiter::core::MeasurementModelInterface::StateFlags = Eigen::Array<bool, StateSize, 1>
Definition at line 40 of file measurement_model_interface.hpp.
StateVector
using kinematic_arbiter::core::MeasurementModelInterface::StateVector = Eigen::Matrix<double, StateSize, 1>
Definition at line 33 of file measurement_model_interface.hpp.
Constructor & Destructor Documentation
MeasurementModelInterface()
kinematic_arbiter::core::MeasurementModelInterface::MeasurementModelInterface (SensorType type, const Eigen::Isometry3d & sensor_pose_in_body_frame = Eigen::Isometry3d::Identity(), const ValidationParams & params = ValidationParams(), const DynamicCovariance & measurement_covariance = Eigen::Matrix<double, kMaxMeasurementDim, kMaxMeasurementDim>::Identity()) inline explicit
Constructor.
Parameters
sensor_pose_in_body_frame Transform from body to sensor frame
params Validation parameters
Definition at line 91 of file measurement_model_interface.hpp.
     : sensor_pose_in_body_frame_(sensor_pose_in_body_frame),
       body_to_sensor_transform_(sensor_pose_in_body_frame.inverse()),
       measurement_covariance_(measurement_covariance),
       validation_params_(params),
       type_(type) {}
~MeasurementModelInterface()
virtual kinematic_arbiter::core::MeasurementModelInterface::~MeasurementModelInterface () virtual default
Virtual destructor.
Member Function Documentation
CanPredictInputAccelerations()
bool kinematic_arbiter::core::MeasurementModelInterface::CanPredictInputAccelerations () const inline
Get whether the prediction model can predict input accelerations.
Returns
True if the prediction model can predict input accelerations
Definition at line 143 of file measurement_model_interface.hpp.
 {return can_predict_input_accelerations_;}
References can_predict_input_accelerations_.
ComputeAuxiliaryData()
MeasurementAuxData kinematic_arbiter::core::MeasurementModelInterface::ComputeAuxiliaryData (const StateVector & state, const StateCovariance & state_covariance, const DynamicVector & measurement) const inline
Compute auxiliary measurement data for use in various algorithms.
Calculates innovation, Jacobian, and innovation covariance once for reuse in validation, update, retrodiction, etc.
Parameters
state Current state estimate x_k
state_covariance Current state covariance P_k
measurement Actual measurement y_k
Returns
Auxiliary measurement data
Definition at line 180 of file measurement_model_interface.hpp.
{
     ValidateMeasurementSize(measurement);
     // Calculate innovation: ν = y_k - h(x_k)
     DynamicVector innovation = measurement - PredictMeasurement(state);
     // Get measurement Jacobian: C_k
     DynamicJacobian jacobian = GetMeasurementJacobian(state);
     // Calculate innovation covariance: S = C_k P_k C_k^T + R
     DynamicCovariance innovation_covariance =
         jacobian * state_covariance * jacobian.transpose() + measurement_covariance_;
     return MeasurementAuxData(innovation, jacobian, innovation_covariance);
   }
References GetMeasurementJacobian(), measurement_covariance_, PredictMeasurement(), and ValidateMeasurementSize().
Referenced by ValidateAndMediate().
GetBodyToSensorTransform()
bool kinematic_arbiter::core::MeasurementModelInterface::GetBodyToSensorTransform (Eigen::Isometry3d & pose) const inline
Get body to sensor transform.
Returns
Body-to-sensor transform
Definition at line 331 of file measurement_model_interface.hpp.
{
     pose = body_to_sensor_transform_;
     return true;
   }
References body_to_sensor_transform_.
GetInitializableStates()
virtual StateFlags kinematic_arbiter::core::MeasurementModelInterface::GetInitializableStates () const pure virtual
Get the states that this sensor can directly initialize.
Returns an array of boolean flags where each element corresponds to a state component. A true value indicates that the sensor can directly initialize that state.
Returns
Flags indicating initializable states
Implemented in kinematic_arbiter::sensors::PositionSensorModel, kinematic_arbiter::sensors::PoseSensorModel, kinematic_arbiter::sensors::ImuSensorModel, and kinematic_arbiter::sensors::BodyVelocitySensorModel.
GetMeasurementCovariance()
const DynamicCovariance& kinematic_arbiter::core::MeasurementModelInterface::GetMeasurementCovariance () const inline
Get current measurement covariance.
Returns
Measurement noise covariance R
Definition at line 149 of file measurement_model_interface.hpp.
{
     return measurement_covariance_;
   }
References measurement_covariance_.
GetMeasurementJacobian()
virtual DynamicJacobian kinematic_arbiter::core::MeasurementModelInterface::GetMeasurementJacobian (const StateVector & state) const pure virtual
Compute the measurement Jacobian H = ∂h/∂x.
Parameters
state Current state estimate x_k
Returns
Measurement Jacobian H (C_k in paper notation)
Implemented in kinematic_arbiter::sensors::PositionSensorModel, kinematic_arbiter::sensors::ImuSensorModel, kinematic_arbiter::sensors::PoseSensorModel, and kinematic_arbiter::sensors::BodyVelocitySensorModel.
Referenced by ComputeAuxiliaryData().
GetModelType()
SensorType kinematic_arbiter::core::MeasurementModelInterface::GetModelType () const inline
Get the type of this sensor model (non-virtual)
Returns
The sensor type enumeration value
Definition at line 378 of file measurement_model_interface.hpp.
{
     return type_;
   }
References type_.
GetPredictionModelInputs()
virtual Eigen::Matrix<double, 6, 1> kinematic_arbiter::core::MeasurementModelInterface::GetPredictionModelInputs (const StateVector & , const StateCovariance & , const DynamicVector & , double) const inline virtual
Get the inputs to the prediction model.
Parameters
state_before_prediction Current state estimate x_k
state_covariance_before_prediction Current state covariance P_k
measurement_after_prediction Actual measurement y_k after prediction of dt
dt Time step in seconds
Returns
Linear and angular acceleration as inputs to the prediction model
Reimplemented in kinematic_arbiter::sensors::ImuSensorModel.
Definition at line 137 of file measurement_model_interface.hpp.
 {return Eigen::Matrix<double, 6, 1>::Zero();};
GetSensorPoseInBodyFrame()
bool kinematic_arbiter::core::MeasurementModelInterface::GetSensorPoseInBodyFrame (Eigen::Isometry3d & pose) const inline
Get sensor pose in body frame.
Returns
Sensor-to-body transform
Definition at line 322 of file measurement_model_interface.hpp.
{
     pose = sensor_pose_in_body_frame_;
     return true;
   }
References sensor_pose_in_body_frame_.
GetValidationParams()
const ValidationParams& kinematic_arbiter::core::MeasurementModelInterface::GetValidationParams () const inline
Get the current validation parameters.
Returns
Current validation parameters
Definition at line 165 of file measurement_model_interface.hpp.
{
     return validation_params_;
   }
References validation_params_.
InitializeState()
virtual StateFlags kinematic_arbiter::core::MeasurementModelInterface::InitializeState (const DynamicVector & measurement, const StateFlags & valid_states, StateVector & state, StateCovariance & covariance) const pure virtual
Initialize state components from a measurement.
This method initializes state components that this sensor can directly observe. Updates both the state vector and covariance matrix for initialized components.
Parameters
measurement The measurement to use for initialization
valid_states Flags indicating which states are valid for use in initialization
state [in/out] The state vector to be initialized
covariance [in/out] The state covariance to be initialized
Returns
Flags indicating which states were initialized
Implemented in kinematic_arbiter::sensors::PositionSensorModel, kinematic_arbiter::sensors::PoseSensorModel, kinematic_arbiter::sensors::ImuSensorModel, and kinematic_arbiter::sensors::BodyVelocitySensorModel.
PredictMeasurement()
virtual DynamicVector kinematic_arbiter::core::MeasurementModelInterface::PredictMeasurement (const StateVector & state) const pure virtual
Predict expected measurement h(x) from state.
Parameters
state Current state estimate x_k
Returns
Expected measurement h(x)
Implemented in kinematic_arbiter::sensors::PositionSensorModel, kinematic_arbiter::sensors::PoseSensorModel, kinematic_arbiter::sensors::ImuSensorModel, and kinematic_arbiter::sensors::BodyVelocitySensorModel.
Referenced by ComputeAuxiliaryData().
reset()
virtual void kinematic_arbiter::core::MeasurementModelInterface::reset () pure virtual
Reset the measurement model to initial state.
Implemented in kinematic_arbiter::sensors::PositionSensorModel, kinematic_arbiter::sensors::PoseSensorModel, kinematic_arbiter::sensors::ImuSensorModel, and kinematic_arbiter::sensors::BodyVelocitySensorModel.
SetSensorPoseInBodyFrame()
bool kinematic_arbiter::core::MeasurementModelInterface::SetSensorPoseInBodyFrame (const Eigen::Isometry3d & pose) inline
Set sensor pose in body frame.
Parameters
pose New sensor-to-body transform
Definition at line 340 of file measurement_model_interface.hpp.
{
     sensor_pose_in_body_frame_ = pose;
     body_to_sensor_transform_ = pose.inverse();
     return true;
   }
References body_to_sensor_transform_, and sensor_pose_in_body_frame_.
SetValidationParams()
void kinematic_arbiter::core::MeasurementModelInterface::SetValidationParams (const ValidationParams & params) inline
Set the validation parameters.
Parameters
params New validation parameters
Definition at line 157 of file measurement_model_interface.hpp.
{
     validation_params_ = params;
   }
References validation_params_.
UpdateCovariance()
void kinematic_arbiter::core::MeasurementModelInterface::UpdateCovariance (const DynamicVector & innovation) inline private
Update measurement covariance with bounded innovation.
Parameters
innovation Measurement innovation
Definition at line 456 of file measurement_model_interface.hpp.
{
     // Define bounds as named constants for clarity
     static const double kMinInnovation = 1e-6;
     static const double kMaxInnovation = 1e6;
     // 1. Clip large values (positive and negative)
     auto clipped = innovation.array().cwiseMax(-kMaxInnovation).cwiseMin(kMaxInnovation);
     // 2. Apply minimum magnitude while preserving sign
     // Formula: sign(x) * max(|x|, kMinInnovation)
     DynamicVector bounded_innovation =
         clipped.sign() * clipped.abs().cwiseMax(kMinInnovation);
     // Update covariance with the adaptive formula
     measurement_covariance_ += (bounded_innovation * bounded_innovation.transpose() -
                                measurement_covariance_) / validation_params_.noise_sample_window;
   }
References measurement_covariance_, kinematic_arbiter::core::MeasurementModelInterface::ValidationParams::noise_sample_window, and validation_params_.
Referenced by ValidateAndMediate().
ValidateAndMediate()
bool kinematic_arbiter::core::MeasurementModelInterface::ValidateAndMediate (const StateVector & state, const StateCovariance & state_covariance, const double & measurement_timestamp, const DynamicVector & measurement, MeasurementAuxData & aux_data) inline
Perform the validation and mediation process.
Parameters
state Current state estimate x_k
state_covariance Current state covariance P_k
measurement_timestamp Measurement timestamp
measurement Actual measurement y_k
aux_data Output parameter for auxiliary measurement data
Returns
Whether filter assumptions hold for this measurement
Definition at line 252 of file measurement_model_interface.hpp.
{
     previous_measurement_data_ = MeasurementData(
       measurement_timestamp,
       measurement,
       measurement_covariance_
     );
     // Compute auxiliary data
     aux_data = ComputeAuxiliaryData(state, state_covariance, measurement);
     // Validate auxiliary data
     if (!ValidateAuxiliaryData(aux_data)) {
       return false;
     }
     // Skip innovation test for forced accept
     if (validation_params_.mediation_action == MediationAction::ForceAccept) {
       UpdateCovariance(aux_data.innovation);
       previous_measurement_data_.covariance = measurement_covariance_;
       return true;
     }
     // Mahalanobis distance: d = ν^T S^-1 ν
     double chi_squared_term = aux_data.innovation.transpose() *
                         aux_data.innovation_covariance.ldlt().solve(
                         aux_data.innovation);
     // Determine threshold for chi-squared test
     double threshold = utils::CalculateChiSquareCriticalValueNDof(
           aux_data.innovation.rows()-1, validation_params_.confidence_level);
     // Check if measurement passes validation
     if (chi_squared_term < threshold) {
       UpdateCovariance(aux_data.innovation);
       previous_measurement_data_.covariance = measurement_covariance_;
       return true;
     }
     // Measurement Apply Mediation Action
     if (validation_params_.mediation_action == MediationAction::AdjustCovariance) {
       // Scale covariance to make chi-squared test pass
       double scale_factor = chi_squared_term / threshold;
       aux_data.innovation_covariance *= scale_factor;
       measurement_covariance_ = aux_data.innovation_covariance - aux_data.jacobian * state_covariance * aux_data.jacobian.transpose();
       previous_measurement_data_.covariance = measurement_covariance_;
       return true;
     }
     // Log warning with metadata when validation fails
     std::cerr << "WARNING: Measurement validation failed for sensor type "
               << SensorTypeToString(type_) << std::endl
               << "  Chi-squared value: " << chi_squared_term
               << ", Threshold: " << threshold << std::endl
               << "  Innovation norm: " << aux_data.innovation.norm()
               << ", Measurement timestamp: " << measurement_timestamp << std::endl;
     // Always return false if validation fails
     return false;
   }
References kinematic_arbiter::core::AdjustCovariance, kinematic_arbiter::utils::CalculateChiSquareCriticalValueNDof(), ComputeAuxiliaryData(), kinematic_arbiter::core::MeasurementModelInterface::ValidationParams::confidence_level, kinematic_arbiter::core::MeasurementModelInterface::MeasurementData::covariance, kinematic_arbiter::core::ForceAccept, kinematic_arbiter::core::MeasurementModelInterface::MeasurementAuxData::innovation, kinematic_arbiter::core::MeasurementModelInterface::MeasurementAuxData::innovation_covariance, kinematic_arbiter::core::MeasurementModelInterface::MeasurementAuxData::jacobian, measurement_covariance_, kinematic_arbiter::core::MeasurementModelInterface::ValidationParams::mediation_action, previous_measurement_data_, kinematic_arbiter::core::SensorTypeToString(), type_, UpdateCovariance(), ValidateAuxiliaryData(), and validation_params_.
ValidateAuxiliaryData()
bool kinematic_arbiter::core::MeasurementModelInterface::ValidateAuxiliaryData (const MeasurementAuxData & aux_data) const inline
Validate auxiliary measurement data (innovation, jacobian, covariance)
Parameters
aux_data Auxiliary measurement data
Returns
true if validation passes, false otherwise
Definition at line 205 of file measurement_model_interface.hpp.
{
     // Check innovation and jacobian for NaN/Inf
     if (!aux_data.innovation.allFinite() || !aux_data.jacobian.allFinite()) {
       std::cerr << "Invalid innovation or jacobian from " << SensorTypeToString(type_) << " sensor" << std::endl;
       return false;
     }
     // Check innovation covariance for NaN/Inf
     if (!aux_data.innovation_covariance.allFinite()) {
       std::cerr << "Innovation covariance contains NaN/Inf from " << SensorTypeToString(type_) << " sensor" << std::endl;
       return false;
     }
     // Check if innovation covariance is well-conditioned
     Eigen::JacobiSVD<DynamicCovariance> svd(aux_data.innovation_covariance);
     double condition_number = svd.singularValues()(0) /
                              std::max(svd.singularValues()(svd.singularValues().size() - 1), 1e-12);
     const double kConditionThreshold = 1e12;
     if (condition_number > kConditionThreshold) {
       std::cerr << "Ill-conditioned innovation covariance (cond=" << condition_number
                 << ") from " << SensorTypeToString(type_) << " sensor" << std::endl;
       return false;
     }
     // Check if LDLT decomposition succeeds (positive definite check)
     Eigen::LDLT<DynamicCovariance> ldlt(aux_data.innovation_covariance);
     if (ldlt.info() != Eigen::Success) {
       std::cerr << "Innovation covariance not positive definite from "
                 << SensorTypeToString(type_) << " sensor" << std::endl;
       return false;
     }
     // All checks passed
     return true;
   }
References kinematic_arbiter::core::MeasurementModelInterface::MeasurementAuxData::innovation, kinematic_arbiter::core::MeasurementModelInterface::MeasurementAuxData::innovation_covariance, kinematic_arbiter::core::MeasurementModelInterface::MeasurementAuxData::jacobian, kinematic_arbiter::core::SensorTypeToString(), and type_.
Referenced by ValidateAndMediate().
ValidateMeasurementAndTime()
bool kinematic_arbiter::core::MeasurementModelInterface::ValidateMeasurementAndTime (const DynamicVector & measurement, double timestamp, double reference_time, double max_delay_window) const inline
Validate measurement and timestamp before any expensive operations.
Parameters
measurement Raw measurement vector
timestamp Measurement timestamp
reference_time Current filter reference time
max_delay_window Maximum delay window for measurements
Returns
bool Whether measurement passed basic validation
Definition at line 391 of file measurement_model_interface.hpp.
{
     // Check for NaN/Inf in measurement
     if (!measurement.allFinite()) {
       std::cerr << "Invalid measurement from " << SensorTypeToString(type_) << " sensor" << std::endl;
       return false;
     }
     // Check measurement size
     ValidateMeasurementSize(measurement);
     // Reference time not yet set (first measurement)
     if (reference_time == std::numeric_limits<double>::lowest()) {
       return true;
     }
     // Check timestamp against delay window
     if (timestamp < reference_time - max_delay_window ||
         timestamp > reference_time + max_delay_window) {
       std::cerr << "Timestamp outside acceptable window for " << SensorTypeToString(type_) << " sensor" << std::endl;
       return false;
     }
     return true;
   }
References kinematic_arbiter::core::SensorTypeToString(), type_, and ValidateMeasurementSize().
ValidateMeasurementSize()
void kinematic_arbiter::core::MeasurementModelInterface::ValidateMeasurementSize (const DynamicVector & measurement) const inline protected
Validate measurement size based on sensor type.
Parameters
measurement Measurement vector to validate
Definition at line 426 of file measurement_model_interface.hpp.
{
         // Validate sensor type is known
     if (type_ == SensorType::Unknown) {
       throw std::invalid_argument("Cannot process measurement with Unknown sensor type");
     }
     if (measurement.size() != GetMeasurementDimension(type_)) {
       throw std::invalid_argument(
           "Measurement size mismatch: expected " +
           std::to_string(GetMeasurementDimension(type_)) +
           ", got " + std::to_string(measurement.size()));
     }
   }
References kinematic_arbiter::core::GetMeasurementDimension(), type_, and kinematic_arbiter::core::Unknown.
Referenced by ComputeAuxiliaryData(), kinematic_arbiter::sensors::BodyVelocitySensorModel::InitializeState(), kinematic_arbiter::sensors::PoseSensorModel::InitializeState(), kinematic_arbiter::sensors::PositionSensorModel::InitializeState(), and ValidateMeasurementAndTime().
Member Data Documentation
body_to_sensor_transform_
Eigen::Isometry3d kinematic_arbiter::core::MeasurementModelInterface::body_to_sensor_transform_ = Eigen::Isometry3d::Identity() protected
Definition at line 476 of file measurement_model_interface.hpp.
Referenced by GetBodyToSensorTransform(), and SetSensorPoseInBodyFrame().
can_predict_input_accelerations_
bool kinematic_arbiter::core::MeasurementModelInterface::can_predict_input_accelerations_ = false protected
Definition at line 479 of file measurement_model_interface.hpp.
Referenced by CanPredictInputAccelerations(), and kinematic_arbiter::sensors::ImuSensorModel::ImuSensorModel().
measurement_covariance_
DynamicCovariance kinematic_arbiter::core::MeasurementModelInterface::measurement_covariance_ protected
Definition at line 477 of file measurement_model_interface.hpp.
Referenced by ComputeAuxiliaryData(), GetMeasurementCovariance(), kinematic_arbiter::sensors::BodyVelocitySensorModel::InitializeState(), kinematic_arbiter::sensors::PoseSensorModel::InitializeState(), kinematic_arbiter::sensors::PositionSensorModel::InitializeState(), kinematic_arbiter::sensors::BodyVelocitySensorModel::reset(), kinematic_arbiter::sensors::ImuSensorModel::reset(), kinematic_arbiter::sensors::PoseSensorModel::reset(), kinematic_arbiter::sensors::PositionSensorModel::reset(), UpdateCovariance(), and ValidateAndMediate().
previous_measurement_data_
MeasurementData kinematic_arbiter::core::MeasurementModelInterface::previous_measurement_data_ protected
Definition at line 480 of file measurement_model_interface.hpp.
Referenced by ValidateAndMediate().
sensor_pose_in_body_frame_
Eigen::Isometry3d kinematic_arbiter::core::MeasurementModelInterface::sensor_pose_in_body_frame_ = Eigen::Isometry3d::Identity() protected
Definition at line 475 of file measurement_model_interface.hpp.
Referenced by kinematic_arbiter::sensors::BodyVelocitySensorModel::GetMeasurementJacobian(), kinematic_arbiter::sensors::PoseSensorModel::GetMeasurementJacobian(), kinematic_arbiter::sensors::PositionSensorModel::GetMeasurementJacobian(), GetSensorPoseInBodyFrame(), kinematic_arbiter::sensors::BodyVelocitySensorModel::InitializeState(), kinematic_arbiter::sensors::PoseSensorModel::InitializeState(), kinematic_arbiter::sensors::PositionSensorModel::InitializeState(), kinematic_arbiter::sensors::BodyVelocitySensorModel::PredictMeasurement(), kinematic_arbiter::sensors::PoseSensorModel::PredictMeasurement(), kinematic_arbiter::sensors::PositionSensorModel::PredictMeasurement(), and SetSensorPoseInBodyFrame().
StateSize
constexpr int kinematic_arbiter::core::MeasurementModelInterface::StateSize = StateIndex::kFullStateSize static constexpr
Definition at line 31 of file measurement_model_interface.hpp.
type_
SensorType kinematic_arbiter::core::MeasurementModelInterface::type_ = SensorType::Unknown protected
Definition at line 481 of file measurement_model_interface.hpp.
Referenced by GetModelType(), ValidateAndMediate(), ValidateAuxiliaryData(), ValidateMeasurementAndTime(), and ValidateMeasurementSize().
validation_params_
ValidationParams kinematic_arbiter::core::MeasurementModelInterface::validation_params_ protected
Definition at line 478 of file measurement_model_interface.hpp.
Referenced by GetValidationParams(), SetValidationParams(), UpdateCovariance(), and ValidateAndMediate().
The documentation for this class was generated from the following file:
/home/spencer/ros2workspace/src/kinematic_arbiter/include/kinematic_arbiter/core/measurement_model_interface.hpp