kinematic_arbiter: kinematic_arbiter::core::StateModelInterface Class Reference
kinematic_arbiter::core::StateModelInterface Class Reference abstract
Interface for state transition models used in Kalman filtering.
#include <state_model_interface.hpp>
Classes
struct Params
Parameters for state model configuration.
Public Types
using StateVector = Eigen::Matrix< double, StateSize, 1 >
using StateMatrix = Eigen::Matrix< double, StateSize, StateSize >
using Vector3d = Eigen::Vector3d
Public Member Functions
void reset ()
Reset the state model to initial state.
StateModelInterface (const Params &params=Params())
Constructor with parameters.
virtual ~StateModelInterface ()=default
Virtual destructor.
virtual StateVector PredictState (const StateVector &state, double dt) const =0
Predict state forward in time: x̂_k^- = f(x̂_{k-1}^+, u_k)
virtual StateMatrix GetTransitionMatrix (const StateVector &state, double dt) const =0
Get the state transition matrix: A_k.
virtual StateVector PredictStateWithInputAccelerations (const StateVector &state, double dt, const Vector3d &linear_acceleration=Vector3d::Zero(), const Vector3d &angular_acceleration=Vector3d::Zero()) const
Predict state forward in time: x̂_k^- = f(x̂_{k-1}^+, u_k)
virtual StateMatrix GetProcessNoiseCovariance (double dt) const
Get the process noise covariance matrix: Q_k.
void UpdateProcessNoise (const StateVector &a_priori_state, const StateVector &a_posteriori_state, double process_to_measurement_ratio, double dt)
Update process noise based on state correction.
const StateMatrix & GetProcessNoise () const
Get the current process noise matrix.
const Params & GetParams () const
Get the state model parameters.
Static Public Attributes
static constexpr int StateSize = StateIndex::kFullStateSize
Protected Attributes
StateVector state_diff_ = StateVector::Zero()
Params params_
StateMatrix process_noise_ = StateMatrix::Identity()
bool state_initialized_ = false
double time_since_reset_ = 0.0
Static Protected Attributes
static constexpr double kMinStateDiff = 1e-6
static constexpr double kMaxStateDiff = 1e6
Detailed Description
Interface for state transition models used in Kalman filtering.
Definition at line 13 of file state_model_interface.hpp.
Member Typedef Documentation
StateMatrix
using kinematic_arbiter::core::StateModelInterface::StateMatrix = Eigen::Matrix<double, StateSize, StateSize>
Definition at line 18 of file state_model_interface.hpp.
StateVector
using kinematic_arbiter::core::StateModelInterface::StateVector = Eigen::Matrix<double, StateSize, 1>
Definition at line 17 of file state_model_interface.hpp.
Vector3d
using kinematic_arbiter::core::StateModelInterface::Vector3d = Eigen::Vector3d
Definition at line 19 of file state_model_interface.hpp.
Constructor & Destructor Documentation
StateModelInterface()
kinematic_arbiter::core::StateModelInterface::StateModelInterface (const Params & params = Params()) inline explicit
Constructor with parameters.
Parameters
params Parameters for this state model
Definition at line 58 of file state_model_interface.hpp.
     : params_(params),
       state_initialized_(false),
       time_since_reset_(0.0) {
     // Initialize process noise with diagonal elements based on parameters
     process_noise_ = StateMatrix::Zero();
     // Set position uncertainty (states 0-2)
     process_noise_.block<3, 3>(0, 0) =
         params_.position_uncertainty_per_second* params_.position_uncertainty_per_second* Eigen::Matrix3d::Identity() / 9.0;
     // Set orientation uncertainty (states 3-6, quaternion)
     process_noise_.block<4, 4>(3, 3) =
         params_.orientation_uncertainty_per_second * params_.orientation_uncertainty_per_second * Eigen::Matrix4d::Identity() / (16.0 * 9.0);
     // Set linear velocity uncertainty (states 7-9)
     process_noise_.block<3, 3>(7, 7) =
         params_.linear_velocity_uncertainty_per_second * params_.linear_velocity_uncertainty_per_second * Eigen::Matrix3d::Identity() / (9.0);
     // Set angular velocity uncertainty (states 10-12)
     process_noise_.block<3, 3>(10, 10) =
         params_.angular_velocity_uncertainty_per_second * params_.angular_velocity_uncertainty_per_second * Eigen::Matrix3d::Identity() / (9.0);
     // Set linear acceleration uncertainty (states 13-15)
     process_noise_.block<3, 3>(13, 13) =
         params_.linear_acceleration_uncertainty_per_second * params_.linear_acceleration_uncertainty_per_second * Eigen::Matrix3d::Identity() / (9.0);
     // Set angular acceleration uncertainty (states 16-18)
     process_noise_.block<3, 3>(16, 16) =
         params_.angular_acceleration_uncertainty_per_second * params_.angular_acceleration_uncertainty_per_second * Eigen::Matrix3d::Identity() / (9.0);
   }
References kinematic_arbiter::core::StateModelInterface::Params::angular_acceleration_uncertainty_per_second, kinematic_arbiter::core::StateModelInterface::Params::angular_velocity_uncertainty_per_second, kinematic_arbiter::core::StateModelInterface::Params::linear_acceleration_uncertainty_per_second, kinematic_arbiter::core::StateModelInterface::Params::linear_velocity_uncertainty_per_second, kinematic_arbiter::core::StateModelInterface::Params::orientation_uncertainty_per_second, params_, kinematic_arbiter::core::StateModelInterface::Params::position_uncertainty_per_second, and process_noise_.
~StateModelInterface()
virtual kinematic_arbiter::core::StateModelInterface::~StateModelInterface () virtual default
Virtual destructor.
Member Function Documentation
GetParams()
const Params& kinematic_arbiter::core::StateModelInterface::GetParams () const inline
Get the state model parameters.
Returns
Const reference to parameters
Definition at line 196 of file state_model_interface.hpp.
 { return params_; }
References params_.
GetProcessNoise()
const StateMatrix& kinematic_arbiter::core::StateModelInterface::GetProcessNoise () const inline
Get the current process noise matrix.
Returns
Current process noise matrix Q̂
Definition at line 187 of file state_model_interface.hpp.
{
     return process_noise_;
   }
References process_noise_.
GetProcessNoiseCovariance()
virtual StateMatrix kinematic_arbiter::core::StateModelInterface::GetProcessNoiseCovariance (double dt) const inline virtual
Get the process noise covariance matrix: Q_k.
Process noise represents uncertainty in the state transition.
Parameters
dt Time step in seconds
Returns
Process noise covariance matrix Q_k
Definition at line 141 of file state_model_interface.hpp.
{
     return process_noise_ * fabs(dt);
   }
References process_noise_.
GetTransitionMatrix()
virtual StateMatrix kinematic_arbiter::core::StateModelInterface::GetTransitionMatrix (const StateVector & state, double dt) const pure virtual
Get the state transition matrix: A_k.
The matrix A_k linearizes the state transition function: A_k = ∂f/∂x evaluated at x̂_{k-1}^+ and u_k
Parameters
state Current state estimate x̂_{k-1}^+
dt Time step in seconds
Returns
State transition matrix A_k
Implemented in kinematic_arbiter::models::RigidBodyStateModel.
PredictState()
virtual StateVector kinematic_arbiter::core::StateModelInterface::PredictState (const StateVector & state, double dt) const pure virtual
Predict state forward in time: x̂_k^- = f(x̂_{k-1}^+, u_k)
Parameters
state Current state estimate x̂_{k-1}^+
dt Time step in seconds
Returns
Predicted next state x̂_k^-
Implemented in kinematic_arbiter::models::RigidBodyStateModel.
Referenced by PredictStateWithInputAccelerations().
PredictStateWithInputAccelerations()
virtual StateVector kinematic_arbiter::core::StateModelInterface::PredictStateWithInputAccelerations (const StateVector & state, double dt, const Vector3d & linear_acceleration = Vector3d::Zero(), const Vector3d & angular_acceleration = Vector3d::Zero()) const inline virtual
Predict state forward in time: x̂_k^- = f(x̂_{k-1}^+, u_k)
Parameters
state Current state estimate x̂_{k-1}^+
dt Time step in seconds
Returns
Predicted next state x̂_k^-
Definition at line 125 of file state_model_interface.hpp.
   {
     StateVector new_state = state;
     new_state.segment<3>(StateIndex::LinearAcceleration::Begin()) = linear_acceleration;
     new_state.segment<3>(StateIndex::AngularAcceleration::Begin()) = angular_acceleration;
     return PredictState(new_state, dt);
   };
References kinematic_arbiter::core::StateIndex::LinearAcceleration::Begin(), kinematic_arbiter::core::StateIndex::AngularAcceleration::Begin(), and PredictState().
reset()
void kinematic_arbiter::core::StateModelInterface::reset () inline
Reset the state model to initial state.
Definition at line 49 of file state_model_interface.hpp.
                {
     process_noise_ = StateMatrix::Identity();
   }
References process_noise_.
UpdateProcessNoise()
void kinematic_arbiter::core::StateModelInterface::UpdateProcessNoise (const StateVector & a_priori_state, const StateVector & a_posteriori_state, double process_to_measurement_ratio, double dt) inline
Update process noise based on state correction.
Implements dynamic process noise estimation using the equation: Q̂_k = Q̂_{k-1} + (ζ·dt·(x̂_k^- - x̂_k^+)(x̂_k^- - x̂_k^+)^T - Q̂_{k-1})/n
Where:
Q̂_k is the new process noise estimate
ζ is the process to measurement noise ratio
dt is the time step
x̂_k^- is the a priori state estimate (before update)
x̂_k^+ is the a posteriori state estimate (after update)
n is the sample window size
Parameters
a_priori_state The a priori state estimate x̂_k^-
a_posteriori_state The a posteriori state estimate x̂_k^+
process_to_measurement_ratio The process to measurement noise ratio (ζ)
dt Time step in seconds
Definition at line 164 of file state_model_interface.hpp.
                  {
     // Compute state correction
     StateVector tmp_state_diff = sqrt(process_to_measurement_ratio) * (a_priori_state - a_posteriori_state).array().abs() / fabs(dt);
     StateVector bounded_diff = (tmp_state_diff.array() < kMinStateDiff).select(0.0, tmp_state_diff.array()).min(kMaxStateDiff);
     // Apply maximum bound to state differences
     state_diff_ += (bounded_diff - state_diff_) / params_.process_noise_window;
     if( (state_diff_.array() > kMinStateDiff).all() ) {
     process_noise_ += (state_diff_ * state_diff_.transpose() - process_noise_) / (params_.process_noise_window);
     }
   }
References kMaxStateDiff, kMinStateDiff, params_, process_noise_, kinematic_arbiter::core::StateModelInterface::Params::process_noise_window, and state_diff_.
Member Data Documentation
kMaxStateDiff
constexpr double kinematic_arbiter::core::StateModelInterface::kMaxStateDiff = 1e6 static constexpr protected
Definition at line 201 of file state_model_interface.hpp.
Referenced by UpdateProcessNoise().
kMinStateDiff
constexpr double kinematic_arbiter::core::StateModelInterface::kMinStateDiff = 1e-6 static constexpr protected
Definition at line 200 of file state_model_interface.hpp.
Referenced by UpdateProcessNoise().
params_
Params kinematic_arbiter::core::StateModelInterface::params_ protected
Definition at line 206 of file state_model_interface.hpp.
Referenced by GetParams(), StateModelInterface(), and UpdateProcessNoise().
process_noise_
StateMatrix kinematic_arbiter::core::StateModelInterface::process_noise_ = StateMatrix::Identity() protected
Definition at line 209 of file state_model_interface.hpp.
Referenced by GetProcessNoise(), GetProcessNoiseCovariance(), reset(), StateModelInterface(), and UpdateProcessNoise().
state_diff_
StateVector kinematic_arbiter::core::StateModelInterface::state_diff_ = StateVector::Zero() protected
Definition at line 203 of file state_model_interface.hpp.
Referenced by UpdateProcessNoise().
state_initialized_
bool kinematic_arbiter::core::StateModelInterface::state_initialized_ = false protected
Definition at line 212 of file state_model_interface.hpp.
StateSize
constexpr int kinematic_arbiter::core::StateModelInterface::StateSize = StateIndex::kFullStateSize static constexpr
Definition at line 16 of file state_model_interface.hpp.
time_since_reset_
double kinematic_arbiter::core::StateModelInterface::time_since_reset_ = 0.0 protected
Definition at line 213 of file state_model_interface.hpp.
The documentation for this class was generated from the following file:
/home/spencer/ros2workspace/src/kinematic_arbiter/include/kinematic_arbiter/core/state_model_interface.hpp