kinematic_arbiter: kinematic_arbiter::models::RigidBodyStateModel Class Reference
kinematic_arbiter::models::RigidBodyStateModel Class Reference
State model for 3D rigid body with quaternion orientation.
#include <rigid_body_state_model.hpp>
Public Types
using Matrix3d = Eigen::Matrix< double, 3, 3 >
using Vector3d = Eigen::Vector3d
using Vector4d = Eigen::Vector4d
using Matrix4d = Eigen::Matrix< double, 4, 4 >
using SIdx = core::StateIndex
Public Types inherited from kinematic_arbiter::core::StateModelInterface
using StateVector = Eigen::Matrix< double, StateSize, 1 >
using StateMatrix = Eigen::Matrix< double, StateSize, StateSize >
using Vector3d = Eigen::Vector3d
Public Member Functions
RigidBodyStateModel (const Params &params=Params())
Construct a new RigidBodyStateModel.
StateVector PredictState (const StateVector &current_state, double time_step) const override
Predict state forward in time: x̂_k^- = f(x̂_{k-1}^+, u_k)
StateMatrix GetTransitionMatrix (const StateVector &current_state, double time_step) const override
Get the state transition matrix: A_k.
Public Member Functions inherited from kinematic_arbiter::core::StateModelInterface
void reset ()
Reset the state model to initial state.
StateModelInterface (const Params &params=Params())
Constructor with parameters.
virtual ~StateModelInterface ()=default
Virtual destructor.
virtual StateVector PredictStateWithInputAccelerations (const StateVector &state, double dt, const Vector3d &linear_acceleration=Vector3d::Zero(), const Vector3d &angular_acceleration=Vector3d::Zero()) const
Predict state forward in time: x̂_k^- = f(x̂_{k-1}^+, u_k)
virtual StateMatrix GetProcessNoiseCovariance (double dt) const
Get the process noise covariance matrix: Q_k.
void UpdateProcessNoise (const StateVector &a_priori_state, const StateVector &a_posteriori_state, double process_to_measurement_ratio, double dt)
Update process noise based on state correction.
const StateMatrix & GetProcessNoise () const
Get the current process noise matrix.
const Params & GetParams () const
Get the state model parameters.
Additional Inherited Members
Static Public Attributes inherited from kinematic_arbiter::core::StateModelInterface
static constexpr int StateSize = StateIndex::kFullStateSize
Protected Attributes inherited from kinematic_arbiter::core::StateModelInterface
StateVector state_diff_ = StateVector::Zero()
Params params_
StateMatrix process_noise_ = StateMatrix::Identity()
bool state_initialized_ = false
double time_since_reset_ = 0.0
Static Protected Attributes inherited from kinematic_arbiter::core::StateModelInterface
static constexpr double kMinStateDiff = 1e-6
static constexpr double kMaxStateDiff = 1e6
Detailed Description
State model for 3D rigid body with quaternion orientation.
Implements a state transition model for a rigid body in 3D space with:
3D position
Quaternion orientation
3D linear velocity
3D angular velocity
3D linear acceleration
3D angular acceleration
The model uses quaternion kinematics for rotation representation to avoid gimbal lock.
Definition at line 30 of file rigid_body_state_model.hpp.
Member Typedef Documentation
Matrix3d
using kinematic_arbiter::models::RigidBodyStateModel::Matrix3d = Eigen::Matrix<double, 3, 3>
Definition at line 33 of file rigid_body_state_model.hpp.
Matrix4d
using kinematic_arbiter::models::RigidBodyStateModel::Matrix4d = Eigen::Matrix<double, 4, 4>
Definition at line 36 of file rigid_body_state_model.hpp.
SIdx
using kinematic_arbiter::models::RigidBodyStateModel::SIdx = core::StateIndex
Definition at line 39 of file rigid_body_state_model.hpp.
Vector3d
using kinematic_arbiter::models::RigidBodyStateModel::Vector3d = Eigen::Vector3d
Definition at line 34 of file rigid_body_state_model.hpp.
Vector4d
using kinematic_arbiter::models::RigidBodyStateModel::Vector4d = Eigen::Vector4d
Definition at line 35 of file rigid_body_state_model.hpp.
Constructor & Destructor Documentation
RigidBodyStateModel()
kinematic_arbiter::models::RigidBodyStateModel::RigidBodyStateModel (const Params & params = Params()) inline explicit
Construct a new RigidBodyStateModel.
Parameters
params State model parameters
Definition at line 45 of file rigid_body_state_model.hpp.
     : core::StateModelInterface(params) {}
Member Function Documentation
GetTransitionMatrix()
StateMatrix kinematic_arbiter::models::RigidBodyStateModel::GetTransitionMatrix (const StateVector & current_state, double time_step) const inline override virtual
Get the state transition matrix: A_k.
The matrix A_k linearizes the state transition function: A_k = ∂f/∂x evaluated at x̂_{k-1}^+ and u_k
Parameters
current_state Current state estimate x̂_{k-1}^+
time_step Time step in seconds
Returns
State transition matrix A_k
Implements kinematic_arbiter::core::StateModelInterface.
Definition at line 140 of file rigid_body_state_model.hpp.
{
     if (fabs(time_step) <= std::numeric_limits<double>::epsilon()) {
       return StateMatrix::Identity();
     }
     StateMatrix jacobian = StateMatrix::Zero();
     // Extract quaternion and normalize
     Eigen::Quaterniond orientation(
       current_state[SIdx::Quaternion::W],
       current_state[SIdx::Quaternion::X],
       current_state[SIdx::Quaternion::Y],
       current_state[SIdx::Quaternion::Z]
     );
     orientation.normalize();
     // Get rotation matrix (world to body frame)
     Matrix3d rotation_matrix_w_to_b = orientation.toRotationMatrix().transpose();
     // Position block - identity for position elements
     jacobian.block<3,3>(SIdx::Position::Begin(), SIdx::Position::Begin()) =
       Matrix3d::Identity();
     // Position wrt linear velocity
     jacobian.block<3,3>(SIdx::Position::Begin(), SIdx::LinearVelocity::Begin()) =
       rotation_matrix_w_to_b * (time_step * Matrix3d::Identity());
     // Position wrt linear acceleration
     jacobian.block<3,3>(SIdx::Position::Begin(), SIdx::LinearAcceleration::Begin()) =
       rotation_matrix_w_to_b * (time_step * time_step * 0.5 * Matrix3d::Identity());
     // Remove coupling between linear and angular position in the jacobian by
     // setting to zero. Derivation of partial of position with respect to the
     // rotation in quaternion form can be found here:
     // http://www.iri.upc.edu/people/jsola/JoanSola/objectes/notes/kinematics.pdf
     jacobian.block<3,4>(SIdx::Position::Begin(), SIdx::Quaternion::Begin()) =
         Eigen::Matrix<double, 3, 4>::Zero();
     // Quaternion self-propagation
     jacobian.block<4,4>(SIdx::Quaternion::Begin(), SIdx::Quaternion::Begin()) =
         Matrix4d::Identity();
     // Extract angular velocity and acceleration components
     const Vector3d angular_velocity =
       current_state.segment<3>(SIdx::AngularVelocity::Begin());
     const Vector3d angular_acceleration =
       current_state.segment<3>(SIdx::AngularAcceleration::Begin());
     // Calculate combined angular motion vector v = 0.5*ω*dt + 0.25*ω̇*dt²
     // This is the same vector used in the quaternion update: q(t+dt) = exp(v) * q(t)
     double t = time_step;
     Vector3d combined_angular_motion = angular_velocity * t + 0.5 * angular_acceleration * t * t;
     double motion_norm = combined_angular_motion.norm();
     // Jacobian terms for quaternion derivatives with respect to angular velocity
     // ∂q/∂ω ≈ (t/2)*I - higher order correction terms
     Matrix3d velocity_term = (t/2.0) * Matrix3d::Identity();
     // Jacobian terms for quaternion derivatives with respect to angular acceleration
     // ∂q/∂ω̇ ≈ (t²/4)*I - higher order correction terms
     Matrix3d accel_term = (t*t/4.0) * Matrix3d::Identity();
     // Apply correction terms when motion is non-zero
     if (motion_norm > std::numeric_limits<double>::min()) {
       // Compute outer product correction based on combined motion
       // This comes from the derivative of the exponential map
       Matrix3d outer_product_correction = (combined_angular_motion * combined_angular_motion.transpose()) /
                                          (motion_norm * motion_norm);
       // Scale for velocity: (t³*||v||)/16 * (v*v^T/||v||²)
       Matrix3d velocity_correction = (t*t*t * motion_norm / 16.0) * outer_product_correction;
       // Scale for acceleration: (t⁴*||v||)/32 * (v*v^T/||v||²)
       Matrix3d accel_correction = (t*t*t*t * motion_norm / 32.0) * outer_product_correction;
       velocity_term -= velocity_correction;
       accel_term -= accel_correction;
     }
     // Create quaternion derivatives for angular velocity components
     // Format: [scalar_part, vector_part_x, vector_part_y, vector_part_z]
     Vector4d dq_dx(
         -0.25 * t * combined_angular_motion[0],  // Scalar part derivative
         velocity_term(0,0), velocity_term(0,1), velocity_term(0,2)  // Vector part derivatives
     );
     Vector4d dq_dy(
         -0.25 * t * combined_angular_motion[1],
         velocity_term(1,0), velocity_term(1,1), velocity_term(1,2)
     );
     Vector4d dq_dz(
         -0.25 * t * combined_angular_motion[2],
         velocity_term(2,0), velocity_term(2,1), velocity_term(2,2)
     );
     // Set the Jacobian block for quaternion wrt angular velocity
     jacobian.block<4,1>(SIdx::Quaternion::Begin(), SIdx::AngularVelocity::X) = dq_dx;
     jacobian.block<4,1>(SIdx::Quaternion::Begin(), SIdx::AngularVelocity::Y) = dq_dy;
     jacobian.block<4,1>(SIdx::Quaternion::Begin(), SIdx::AngularVelocity::Z) = dq_dz;
     // Create quaternion derivatives for angular acceleration components
     // Format: [scalar_part, vector_part_x, vector_part_y, vector_part_z]
     Vector4d dq_dax(
         -0.125 * t * t * combined_angular_motion[0],  // Scalar part derivative
         accel_term(0,0), accel_term(0,1), accel_term(0,2)  // Vector part derivatives
     );
     Vector4d dq_day(
         -0.125 * t * t * combined_angular_motion[1],
         accel_term(1,0), accel_term(1,1), accel_term(1,2)
     );
     Vector4d dq_daz(
         -0.125 * t * t * combined_angular_motion[2],
         accel_term(2,0), accel_term(2,1), accel_term(2,2)
     );
     // Set the Jacobian block for quaternion wrt angular acceleration
     jacobian.block<4,1>(SIdx::Quaternion::Begin(), SIdx::AngularAcceleration::X) = dq_dax;
     jacobian.block<4,1>(SIdx::Quaternion::Begin(), SIdx::AngularAcceleration::Y) = dq_day;
     jacobian.block<4,1>(SIdx::Quaternion::Begin(), SIdx::AngularAcceleration::Z) = dq_daz;
     // Velocity blocks - identity for velocity elements
     jacobian.block<3,3>(SIdx::LinearVelocity::Begin(), SIdx::LinearVelocity::Begin()) =
       Matrix3d::Identity();
     // Linear velocity wrt linear acceleration
     jacobian.block<3,3>(SIdx::LinearVelocity::Begin(), SIdx::LinearAcceleration::Begin()) =
       time_step * Matrix3d::Identity();
     // Angular velocity blocks - identity for angular velocity elements
     jacobian.block<3,3>(SIdx::AngularVelocity::Begin(), SIdx::AngularVelocity::Begin()) =
       Matrix3d::Identity();
     // Angular velocity wrt angular acceleration
     jacobian.block<3,3>(SIdx::AngularVelocity::Begin(), SIdx::AngularAcceleration::Begin()) =
       time_step * Matrix3d::Identity();
     // Acceleration blocks are modelled as zero (no change)
     // Velocity blocks - identity for velocity elements
     jacobian.block<3,3>(SIdx::LinearVelocity::Begin(), SIdx::LinearVelocity::Begin()) =
       Matrix3d::Identity();
     // Linear velocity wrt linear acceleration
     jacobian.block<3,3>(SIdx::LinearVelocity::Begin(), SIdx::LinearAcceleration::Begin()) =
       time_step * Matrix3d::Identity();
     // Angular velocity blocks - identity for angular velocity elements
     jacobian.block<3,3>(SIdx::AngularVelocity::Begin(), SIdx::AngularVelocity::Begin()) =
       Matrix3d::Identity();
     // Angular velocity wrt angular acceleration
     jacobian.block<3,3>(SIdx::AngularVelocity::Begin(), SIdx::AngularAcceleration::Begin()) =
       time_step * Matrix3d::Identity();
     jacobian.block<3,3>(SIdx::AngularAcceleration::Begin(), SIdx::AngularAcceleration::Begin()) =
       std::exp(-kLambda * time_step) * Matrix3d::Identity();
     jacobian.block<3,3>(SIdx::LinearAcceleration::Begin(), SIdx::LinearAcceleration::Begin()) =
       std::exp(-kLambda * time_step) * Matrix3d::Identity();
     return jacobian;
   }
References kinematic_arbiter::core::StateIndex::Position::Begin(), kinematic_arbiter::core::StateIndex::Quaternion::Begin(), kinematic_arbiter::core::StateIndex::LinearVelocity::Begin(), kinematic_arbiter::core::StateIndex::AngularVelocity::Begin(), kinematic_arbiter::core::StateIndex::LinearAcceleration::Begin(), kinematic_arbiter::core::StateIndex::AngularAcceleration::Begin(), kinematic_arbiter::models::anonymous_namespace{rigid_body_state_model.hpp}::kLambda, kinematic_arbiter::core::StateIndex::Quaternion::W, kinematic_arbiter::core::StateIndex::Quaternion::X, kinematic_arbiter::core::StateIndex::AngularVelocity::X, kinematic_arbiter::core::StateIndex::AngularAcceleration::X, kinematic_arbiter::core::StateIndex::Quaternion::Y, kinematic_arbiter::core::StateIndex::AngularVelocity::Y, kinematic_arbiter::core::StateIndex::AngularAcceleration::Y, kinematic_arbiter::core::StateIndex::Quaternion::Z, kinematic_arbiter::core::StateIndex::AngularVelocity::Z, and kinematic_arbiter::core::StateIndex::AngularAcceleration::Z.
PredictState()
StateVector kinematic_arbiter::models::RigidBodyStateModel::PredictState (const StateVector & current_state, double time_step) const inline override virtual
Predict state forward in time: x̂_k^- = f(x̂_{k-1}^+, u_k)
Parameters
current_state Current state estimate x̂_{k-1}^+
time_step Time step in seconds
Returns
Predicted next state x̂_k^-
Implements kinematic_arbiter::core::StateModelInterface.
Definition at line 55 of file rigid_body_state_model.hpp.
{
     StateVector new_states = current_state;
     if (fabs(time_step) <= std::numeric_limits<double>::epsilon()) {
       return new_states;
     }
     // Extract quaternion and normalize
     Eigen::Quaterniond orientation(
       current_state[SIdx::Quaternion::W],
       current_state[SIdx::Quaternion::X],
       current_state[SIdx::Quaternion::Y],
       current_state[SIdx::Quaternion::Z]
     );
     orientation.normalize();
     // Get rotation matrix
     Matrix3d rotation_matrix_b_to_w = orientation.toRotationMatrix();
     // Extract velocity and acceleration components
     const Vector3d linear_velocity =
       current_state.segment<3>(SIdx::LinearVelocity::Begin());
     const Vector3d angular_velocity =
       current_state.segment<3>(SIdx::AngularVelocity::Begin());
     const Vector3d linear_acceleration =
       current_state.segment<3>(SIdx::LinearAcceleration::Begin());
     const Vector3d angular_acceleration =
       current_state.segment<3>(SIdx::AngularAcceleration::Begin());
     // Linear XYZ Position Prediction Model
     new_states.segment<3>(SIdx::Position::Begin()) +=
       rotation_matrix_b_to_w * ((linear_velocity + time_step * 0.5 * linear_acceleration) * time_step);
     // Angular Position (Quaternion) Prediction Model
     // Use quaternion kinematics with angular acceleration: q(t+dt) = exp(0.5*ω*dt + 0.25*ω̇*dt²) * q(t)
     Eigen::Quaterniond delta_q;
     // Calculate combined angular motion vector v = 0.5*ω*dt + 0.25*ω̇*dt²
     // This is the same vector used in the quaternion update: q(t+dt) = exp(v) * q(t)
     double t = time_step;
     Vector3d combined_angular_motion = angular_velocity * t + 0.5 * angular_acceleration * t * t;
     double motion_norm = combined_angular_motion.norm();
     if (motion_norm > std::numeric_limits<double>::min()) {
       Vector3d axis = combined_angular_motion / motion_norm;
       double angle = motion_norm;
       delta_q = Eigen::Quaterniond(Eigen::AngleAxisd(angle, axis));
     } else {
       delta_q = Eigen::Quaterniond::Identity();
     }
     Eigen::Quaterniond new_quaternion = delta_q * orientation;
     new_quaternion.normalize();
     new_states[SIdx::Quaternion::W] = new_quaternion.w();
     new_states[SIdx::Quaternion::X] = new_quaternion.x();
     new_states[SIdx::Quaternion::Y] = new_quaternion.y();
     new_states[SIdx::Quaternion::Z] = new_quaternion.z();
     // Velocity prediction (integrate acceleration)
     new_states.segment<3>(SIdx::LinearVelocity::Begin()) += time_step * linear_acceleration;
     new_states.segment<3>(SIdx::AngularVelocity::Begin()) += time_step * angular_acceleration;
     // Acceleration is modelled as exponential decay: a(t+dt) = a(t) * exp(-lambda * dt)
     // With lambda = 46.05, acceleration decays to near zero within 0.1s
     new_states.segment<3>(SIdx::LinearAcceleration::Begin()) =
         linear_acceleration * std::exp(-kLambda * time_step);
     new_states.segment<3>(SIdx::AngularAcceleration::Begin()) =
         angular_acceleration * std::exp(-kLambda * time_step);
     return new_states;
   }
References kinematic_arbiter::core::StateIndex::Position::Begin(), kinematic_arbiter::core::StateIndex::LinearVelocity::Begin(), kinematic_arbiter::core::StateIndex::AngularVelocity::Begin(), kinematic_arbiter::core::StateIndex::LinearAcceleration::Begin(), kinematic_arbiter::core::StateIndex::AngularAcceleration::Begin(), kinematic_arbiter::models::anonymous_namespace{rigid_body_state_model.hpp}::kLambda, kinematic_arbiter::core::StateIndex::Quaternion::W, kinematic_arbiter::core::StateIndex::Quaternion::X, kinematic_arbiter::core::StateIndex::Quaternion::Y, and kinematic_arbiter::core::StateIndex::Quaternion::Z.
The documentation for this class was generated from the following file:
/home/spencer/ros2workspace/src/kinematic_arbiter/include/kinematic_arbiter/models/rigid_body_state_model.hpp