kinematic_arbiter: kinematic_arbiter::core Namespace Reference
kinematic_arbiter::core Namespace Reference
Namespaces
anonymous_namespace{measurement_model_interface.hpp}
Classes
class MeasurementModelInterface
Interface for measurement models with assumption validation.
class MediatedKalmanFilter
MediatedKalmanFilter implements a Kalman filter with chi-squared validation.
struct MeasurementDimension
Template specialization to get measurement dimension at compile time.
struct MeasurementDimension< SensorType::Position >
struct MeasurementDimension< SensorType::Pose >
struct MeasurementDimension< SensorType::BodyVelocity >
struct MeasurementDimension< SensorType::Imu >
struct MeasurementDimension< SensorType::Unknown >
struct StateIndex
Base state indices for common state vector elements.
class StateModelInterface
Interface for state transition models used in Kalman filtering.
Typedefs
template<SensorType Type>
using MeasurementVector = Eigen::Matrix< double, MeasurementDimension< Type >::value, 1 >
Get measurement vector type for a sensor type.
Enumerations
enum class MediationAction { ForceAccept , Reject , AdjustCovariance }
Possible corrective actions when filter assumptions are violated.
enum class SensorType {
Position , Pose , BodyVelocity , Imu ,
Unknown
}
Enumeration of sensor types with built-in dimension information.
Functions
int GetMeasurementDimension (SensorType type)
Runtime function to get measurement dimension from sensor type.
std::string SensorTypeToString (SensorType type)
Convert sensor type to string.
std::vector< std::string > GetInitializableStateNames (const Eigen::Array< bool, 1, StateIndex::kFullStateSize > &initializable_states)
Typedef Documentation
MeasurementVector
template<SensorType Type> using kinematic_arbiter::core::MeasurementVector = typedef Eigen::Matrix<double, MeasurementDimension<Type>::value, 1>
Get measurement vector type for a sensor type.
Definition at line 37 of file sensor_types.hpp.
Enumeration Type Documentation
MediationAction
enum kinematic_arbiter::core::MediationAction strong
Possible corrective actions when filter assumptions are violated.
These actions define how to respond when a measurement fails validation.
Enumerator
ForceAccept
Reject
AdjustCovariance
Definition at line 11 of file mediation_types.hpp.
{
   ForceAccept,     // Proceed with measurement despite validation failure
   Reject,          // Reject the measurement entirely
   AdjustCovariance // Adjust covariance to make measurement valid
 };
SensorType
enum kinematic_arbiter::core::SensorType strong
Enumeration of sensor types with built-in dimension information.
Enumerator
Position
Pose
BodyVelocity
Imu
Unknown
Definition at line 13 of file sensor_types.hpp.
                       {
   Position,     // 3D position (x, y, z)
   Pose,         // 7D pose (position + quaternion)
   BodyVelocity, // 6D velocity (linear + angular)
   Imu,          // 6D IMU (acceleration + angular velocity)
   Unknown       // Unknown type
 };
Function Documentation
GetInitializableStateNames()
std::vector<std::string> kinematic_arbiter::core::GetInitializableStateNames (const Eigen::Array< bool, 1, StateIndex::kFullStateSize > & initializable_states) inline
Definition at line 85 of file state_index.hpp.
{
     // Map of state indices to their names
     static const std::unordered_map<int, std::string> index_to_name = {
         {StateIndex::Position::X, "Position X"},
         {StateIndex::Position::Y, "Position Y"},
         {StateIndex::Position::Z, "Position Z"},
         {StateIndex::Quaternion::W, "Quaternion W"},
         {StateIndex::Quaternion::X, "Quaternion X"},
         {StateIndex::Quaternion::Y, "Quaternion Y"},
         {StateIndex::Quaternion::Z, "Quaternion Z"},
         {StateIndex::LinearVelocity::X, "Linear Velocity X"},
         {StateIndex::LinearVelocity::Y, "Linear Velocity Y"},
         {StateIndex::LinearVelocity::Z, "Linear Velocity Z"},
         {StateIndex::AngularVelocity::X, "Angular Velocity X"},
         {StateIndex::AngularVelocity::Y, "Angular Velocity Y"},
         {StateIndex::AngularVelocity::Z, "Angular Velocity Z"},
         {StateIndex::LinearAcceleration::X, "Linear Acceleration X"},
         {StateIndex::LinearAcceleration::Y, "Linear Acceleration Y"},
         {StateIndex::LinearAcceleration::Z, "Linear Acceleration Z"},
         {StateIndex::AngularAcceleration::X, "Angular Acceleration X"},
         {StateIndex::AngularAcceleration::Y, "Angular Acceleration Y"},
         {StateIndex::AngularAcceleration::Z, "Angular Acceleration Z"}
     };
     // Vector to store the names of the initializable states
     std::vector<std::string> state_names;
     // Populate the vector with names based on the indices
     for (int index : initializable_states) {
         auto it = index_to_name.find(index);
         if (it != index_to_name.end()) {
             state_names.push_back(it->second);
         }
     }
     return state_names;
 }
References kinematic_arbiter::core::StateIndex::Quaternion::W, kinematic_arbiter::core::StateIndex::Position::X, kinematic_arbiter::core::StateIndex::Quaternion::X, kinematic_arbiter::core::StateIndex::LinearVelocity::X, kinematic_arbiter::core::StateIndex::AngularVelocity::X, kinematic_arbiter::core::StateIndex::LinearAcceleration::X, kinematic_arbiter::core::StateIndex::AngularAcceleration::X, kinematic_arbiter::core::StateIndex::Position::Y, kinematic_arbiter::core::StateIndex::Quaternion::Y, kinematic_arbiter::core::StateIndex::LinearVelocity::Y, kinematic_arbiter::core::StateIndex::AngularVelocity::Y, kinematic_arbiter::core::StateIndex::LinearAcceleration::Y, kinematic_arbiter::core::StateIndex::AngularAcceleration::Y, kinematic_arbiter::core::StateIndex::Position::Z, kinematic_arbiter::core::StateIndex::Quaternion::Z, kinematic_arbiter::core::StateIndex::LinearVelocity::Z, kinematic_arbiter::core::StateIndex::AngularVelocity::Z, kinematic_arbiter::core::StateIndex::LinearAcceleration::Z, and kinematic_arbiter::core::StateIndex::AngularAcceleration::Z.
GetMeasurementDimension()
int kinematic_arbiter::core::GetMeasurementDimension (SensorType type) inline
Runtime function to get measurement dimension from sensor type.
This function provides the same information as the MeasurementDimension template but can be used at runtime with non-constexpr types.
Parameters
type The sensor type to query
Returns
int The measurement dimension for the given sensor type
Definition at line 48 of file sensor_types.hpp.
{
   switch (type) {
     case SensorType::Position:     return MeasurementDimension<SensorType::Position>::value;
     case SensorType::Pose:         return MeasurementDimension<SensorType::Pose>::value;
     case SensorType::BodyVelocity: return MeasurementDimension<SensorType::BodyVelocity>::value;
     case SensorType::Imu:          return MeasurementDimension<SensorType::Imu>::value;
     case SensorType::Unknown:      return MeasurementDimension<SensorType::Unknown>::value;
   }
   return -1; // Unknown type
 }
References BodyVelocity, Imu, Pose, Position, and Unknown.
Referenced by kinematic_arbiter::ros2::simulation::SensorPublisher< MsgType >::publish(), and kinematic_arbiter::core::MeasurementModelInterface::ValidateMeasurementSize().
SensorTypeToString()
std::string kinematic_arbiter::core::SensorTypeToString (SensorType type) inline
Convert sensor type to string.
Definition at line 62 of file sensor_types.hpp.
{
   switch (type) {
     case SensorType::Position:     return "Position";
     case SensorType::Pose:         return "Pose";
     case SensorType::BodyVelocity: return "BodyVelocity";
     case SensorType::Imu:          return "Imu";
     case SensorType::Unknown:      return "Unknown";
   }
   return "Unknown";
 }
References BodyVelocity, Imu, Pose, Position, and Unknown.
Referenced by kinematic_arbiter::ros2::SensorHandler< MsgType >::SensorHandler(), kinematic_arbiter::ros2::simulation::SensorPublisher< MsgType >::SensorPublisher(), kinematic_arbiter::core::MeasurementModelInterface::ValidateAndMediate(), kinematic_arbiter::core::MeasurementModelInterface::ValidateAuxiliaryData(), and kinematic_arbiter::core::MeasurementModelInterface::ValidateMeasurementAndTime().