kinematic_arbiter: kinematic_arbiter::utils Namespace Reference
kinematic_arbiter::utils Namespace Reference
Classes
struct ChiSquareCriticalValue
Critical value for chi-square test at a specific confidence level.
struct Figure8Config
Configuration for Figure-8 trajectory generation.
Functions
double InterpolatedCriticalValue (double confidence_level, ChiSquareCriticalValue lower, ChiSquareCriticalValue upper)
Interpolate between two critical values.
double CalculateChiSquareCriticalValue1Dof (double confidence_level)
Calculate chi-square critical value for 1 degree of freedom.
double CalculateChiSquareCriticalValueNDof (size_t dof_index, double confidence_level)
Calculate chi-square critical value for N degrees of freedom.
template<typename Generator , typename Derived >
Eigen::VectorXd generateMultivariateNoise (const Eigen::MatrixBase< Derived > &covariance, Generator &generator)
Generate multivariate normal noise with given covariance.
Eigen::Matrix< double, core::StateIndex::kFullStateSize, 1 > Figure8Trajectory (double time, const Figure8Config &config=Figure8Config())
Generates a figure-8 trajectory for testing.
Variables
constexpr size_t kMaxChiSquareDof = 7
Maximum degrees of freedom for chi-square distribution.
constexpr double kFuzzyMoreThanZero = 1e-10
constexpr std::size_t kNumChiSquareCriticalValues = 13U
constexpr std::array< std::array< ChiSquareCriticalValue, kNumChiSquareCriticalValues >, kMaxChiSquareDof > kChiSquareCriticalValues
Chi-square critical values table.
Function Documentation
CalculateChiSquareCriticalValue1Dof()
double kinematic_arbiter::utils::CalculateChiSquareCriticalValue1Dof (double confidence_level)
Calculate chi-square critical value for 1 degree of freedom.
Parameters
confidence_level Confidence level (0-1)
Returns
Chi-square critical value
Definition at line 20 of file statistical_utils.cpp.
{
   // Index 0 corresponds to 1 DOF
   return CalculateChiSquareCriticalValueNDof(0, confidence_level);
 }
References CalculateChiSquareCriticalValueNDof().
CalculateChiSquareCriticalValueNDof()
double kinematic_arbiter::utils::CalculateChiSquareCriticalValueNDof (size_t dof_index, double confidence_level)
Calculate chi-square critical value for N degrees of freedom.
Parameters
dof_index Index of degrees of freedom (0-6)
confidence_level Confidence level (0-1)
Returns
Chi-square critical value
Definition at line 25 of file statistical_utils.cpp.
{
   // Check if the requested degrees of freedom is supported
   if (dof_index >= kMaxChiSquareDof) {
     throw std::invalid_argument("Unsupported degrees of freedom: " +
                                std::to_string(dof_index) +
                                ". Maximum supported DoF is " +
                                std::to_string(kMaxChiSquareDof));
   }
   if (confidence_level <
       kChiSquareCriticalValues[dof_index].front().confidence) {
     return kChiSquareCriticalValues[dof_index].front().critical_value;
   }
   // Binary search considered but array is small
   for (size_t index = 1U; index < kChiSquareCriticalValues[dof_index].size();
        ++index) {
     if (confidence_level <
         kChiSquareCriticalValues[dof_index][index].confidence) {
       return InterpolatedCriticalValue(
           confidence_level, kChiSquareCriticalValues[dof_index][index - 1U],
           kChiSquareCriticalValues[dof_index][index]);
     }
   }
   return kChiSquareCriticalValues[dof_index].back().critical_value;
 }
References InterpolatedCriticalValue(), kChiSquareCriticalValues, and kMaxChiSquareDof.
Referenced by CalculateChiSquareCriticalValue1Dof(), kinematic_arbiter::sensors::ImuSensorModel::IsStationary(), and kinematic_arbiter::core::MeasurementModelInterface::ValidateAndMediate().
Figure8Trajectory()
Eigen::Matrix<double, core::StateIndex::kFullStateSize, 1> kinematic_arbiter::utils::Figure8Trajectory (double time, const Figure8Config & config = Figure8Config())
Generates a figure-8 trajectory for testing.
Creates a smooth figure-8 trajectory with position, velocity and acceleration. This is useful for testing state prediction and measurement models.
Parameters
time Current time in seconds
config Configuration parameters for the trajectory (optional)
Returns
State vector containing position, orientation, velocity and acceleration
Definition at line 31 of file trajectory_utils.hpp.
{
   using SIdx = core::StateIndex;
   using StateVector = Eigen::Matrix<double, SIdx::kFullStateSize, 1>;
   // Trajectory parameters
   const double a = config.length * 0.5;        // x amplitude
   const double b = config.width * 0.5;         // y amplitude
   const double c = config.width * std::tan(config.width_slope); // z amplitude
   // Period and frequency calculations
   const double T = M_PI * std::sqrt(a*a + 4*(b*b + c*c)) / config.max_velocity;
   const double w1 = 2 * M_PI / T;    // y,z frequency
   const double w2 = w1 * 0.5;        // x frequency
   const double t = time;             // current time
   // Create state vector
   StateVector states = StateVector::Zero();
   // Position vector in world frame
   Eigen::Vector3d position(
       a * std::cos(w2 * t),
       b * std::sin(w1 * t),
       c * std::sin(w1 * t));
   // Store position
   states.segment<3>(SIdx::Position::Begin()) = position;
   // Linear Inertial (World Frame) Velocity
   Eigen::Vector3d i_v(
       -a * w2 * std::sin(w2 * t),
       b * w1 * std::cos(w1 * t),
       c * w1 * std::cos(w1 * t));
   // Linear Inertial (World Frame) Acceleration
   Eigen::Vector3d i_a(
       -a * w2 * w2 * std::cos(w2 * t),
       -b * w1 * w1 * std::sin(w1 * t),
       -c * w1 * w1 * std::sin(w1 * t));
   // Linear Inertial (World Frame) Jerk
   Eigen::Vector3d i_j(
       a * w2 * w2 * w2 * std::sin(w2 * t),
       -b * w1 * w1 * w1 * std::cos(w1 * t),
       -c * w1 * w1 * w1 * std::cos(w1 * t));
   // Current Orientation (body X aligned with velocity)
   Eigen::Quaterniond orientation;
   orientation.setFromTwoVectors(Eigen::Vector3d::UnitX(), i_v.normalized());
   orientation.normalize();
   // Store quaternion
   states[SIdx::Quaternion::W] = orientation.w();
   states[SIdx::Quaternion::X] = orientation.x();
   states[SIdx::Quaternion::Y] = orientation.y();
   states[SIdx::Quaternion::Z] = orientation.z();
   // Convert world velocity to body frame
   Eigen::Vector3d b_v = orientation.inverse() * i_v;
   states.segment<3>(SIdx::LinearVelocity::Begin()) = b_v;
   // 1. Compute angular velocity in world frame
   Eigen::Vector3d omega_world;
   if (i_v.squaredNorm() > 1e-9) {
       omega_world = i_v.cross(i_a) / i_v.squaredNorm();
   } else {
       omega_world.setZero();
   }
   // 2. Transform to body frame
   Eigen::Vector3d omega_body = orientation.inverse() * omega_world;
   states.segment<3>(SIdx::AngularVelocity::Begin()) = omega_body;
   // 3. Compute body-frame acceleration PROPERLY
   Eigen::Vector3d b_a = orientation.inverse() * i_a;
   b_a -= 2 * omega_body.cross(b_v); // Full Coriolis compensation
   states.segment<3>(SIdx::LinearAcceleration::Begin()) = b_a;
   // 4. Angular acceleration (derivative of omega_world)
   Eigen::Vector3d alpha_world;
   if (i_v.squaredNorm() > 1e-9) {
       alpha_world = (i_v.cross(i_j) * i_v.squaredNorm() -
                     2 * i_v.cross(i_a) * i_v.dot(i_a))
                     / (i_v.squaredNorm() * i_v.squaredNorm());
   } else {
       alpha_world.setZero();
   }
   // 5. Transform to body frame
   Eigen::Vector3d alpha_body = orientation.inverse() * alpha_world;
   states.segment<3>(SIdx::AngularAcceleration::Begin()) = alpha_body;
   // 6. Extract and store roll rate (rotation about body X axis)
   double roll_rate = omega_body.dot(Eigen::Vector3d::UnitX());
   states[SIdx::AngularVelocity::X] = roll_rate;
   // 7. Extract and store roll acceleration (about body X axis)
   double roll_accel = alpha_body.dot(Eigen::Vector3d::UnitX());
   states[SIdx::AngularAcceleration::X] = roll_accel;
   return states;
 }
Referenced by kinematic_arbiter::ros2::simulation::Figure8SimulatorNode::update().
generateMultivariateNoise()
template<typename Generator , typename Derived > Eigen::VectorXd kinematic_arbiter::utils::generateMultivariateNoise (const Eigen::MatrixBase< Derived > & covariance, Generator & generator)
Generate multivariate normal noise with given covariance.
Template Parameters
Generator Random number generator type
Derived Eigen matrix type for covariance
Parameters
covariance Covariance matrix (must be positive definite)
generator Random number generator
Returns
Noise vector with specified covariance
Exceptions
std::invalid_argument if covariance is not positive definite
Definition at line 198 of file statistical_utils.hpp.
{
   const int size = covariance.rows();
   // Verify the covariance matrix is square
   if (covariance.rows() != covariance.cols()) {
     throw std::invalid_argument("Covariance matrix must be square");
   }
   // Compute the Cholesky decomposition
   Eigen::LLT<Eigen::MatrixXd> llt(covariance);
   // Check if the covariance matrix is positive definite
   if (llt.info() != Eigen::Success) {
     throw std::invalid_argument("Covariance matrix must be positive definite");
   }
   // Get the lower triangular matrix L from the decomposition
   Eigen::MatrixXd L = llt.matrixL();
   // Create standard normal distribution
   std::normal_distribution<double> normal_dist(0.0, 1.0);
   // Generate standard normal samples
   Eigen::VectorXd z(size);
   for (int i = 0; i < size; ++i) {
     z(i) = normal_dist(generator);
   }
   // Transform to desired covariance: x = L*z
   return L * z;
 }
Referenced by kinematic_arbiter::ros2::simulation::SensorPublisher< MsgType >::publish().
InterpolatedCriticalValue()
double kinematic_arbiter::utils::InterpolatedCriticalValue (double confidence_level, ChiSquareCriticalValue lower, ChiSquareCriticalValue upper)
Interpolate between two critical values.
Parameters
confidence_level Target confidence level
lower Lower critical value data point
upper Upper critical value data point
Returns
Interpolated critical value
Definition at line 8 of file statistical_utils.cpp.
{
   double confidence_spread = upper.confidence - lower.confidence;
   if (std::fabs(confidence_spread) < kFuzzyMoreThanZero) {
     return upper.critical_value;
   }
   double portion = (confidence_level - lower.confidence) / confidence_spread;
   return lower.critical_value +
          portion * (upper.critical_value - lower.critical_value);
 }
References kinematic_arbiter::utils::ChiSquareCriticalValue::confidence, kinematic_arbiter::utils::ChiSquareCriticalValue::critical_value, and kFuzzyMoreThanZero.
Referenced by CalculateChiSquareCriticalValueNDof().
Variable Documentation
kChiSquareCriticalValues
constexpr std::array< std::array<ChiSquareCriticalValue, kNumChiSquareCriticalValues>, kMaxChiSquareDof> kinematic_arbiter::utils::kChiSquareCriticalValues constexpr
Chi-square critical values table.
These values are generated using the integration of the chi square distribution from 0 to the critical value resulting a given confidence level. Reference: https://www.itl.nist.gov/div898/handbook/eda/section3/eda3674.htm
Definition at line 42 of file statistical_utils.hpp.
Referenced by CalculateChiSquareCriticalValueNDof().
kFuzzyMoreThanZero
constexpr double kinematic_arbiter::utils::kFuzzyMoreThanZero = 1e-10 constexpr
Definition at line 29 of file statistical_utils.hpp.
Referenced by InterpolatedCriticalValue().
kMaxChiSquareDof
constexpr size_t kinematic_arbiter::utils::kMaxChiSquareDof = 7 constexpr
Maximum degrees of freedom for chi-square distribution.
Definition at line 18 of file statistical_utils.hpp.
Referenced by CalculateChiSquareCriticalValueNDof().
kNumChiSquareCriticalValues
constexpr std::size_t kinematic_arbiter::utils::kNumChiSquareCriticalValues = 13U constexpr
Definition at line 30 of file statistical_utils.hpp.