name: ROS 2 CI

on:
  pull_request:
  push:
    branches:
      - master
      - main

jobs:
  python_only_build:
    name: Python-Only Build
    runs-on: ubuntu-22.04
    container:
      image: ros:humble
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y python3-pip python3-pytest
          pip3 install pytest-cov

      - name: Build and test (Python only)
        run: |
          . /opt/ros/humble/setup.sh
          mkdir -p ~/ros2_ws/src
          cp -r $GITHUB_WORKSPACE ~/ros2_ws/src/kinematic_arbiter
          cd ~/ros2_ws
          colcon build --packages-select kinematic_arbiter --cmake-args -DBUILD_PYTHON_ONLY=ON
          colcon test --packages-select kinematic_arbiter --event-handlers=console_direct+
          colcon test-result --verbose

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: python-only-logs
          path: ~/ros2_ws/log
        if: always()

  full_build:
    name: Full Build (Python + C++)
    runs-on: ubuntu-22.04
    container:
      image: ros:humble
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Drake
        run: |
          apt-get update
          apt-get install -y curl gnupg lsb-release
          curl -sSL https://drake-apt.csail.mit.edu/drake.asc | gpg --dearmor - > /etc/apt/trusted.gpg.d/drake.gpg
          echo "deb [arch=amd64] https://drake-apt.csail.mit.edu/$(lsb_release -cs) $(lsb_release -cs) main" > /etc/apt/sources.list.d/drake.list
          apt-get update
          apt-get install -y drake

      - name: Install dependencies
        run: |
          apt-get install -y python3-pip python3-pytest
          pip3 install pytest-cov

      - name: Build and test (Full)
        run: |
          . /opt/ros/humble/setup.sh
          mkdir -p ~/ros2_ws/src
          cp -r $GITHUB_WORKSPACE ~/ros2_ws/src/kinematic_arbiter
          cd ~/ros2_ws
          colcon build --packages-select kinematic_arbiter
          colcon test --packages-select kinematic_arbiter --event-handlers=console_direct+
          colcon test-result --verbose
        # This step may fail until C++ implementation is complete
        continue-on-error: true

      - name: Upload logs
        uses: actions/upload-artifact@v3
        with:
          name: full-build-logs
          path: ~/ros2_ws/log
        if: always()
